/**
 * Aktuelle deutsche Kfz-Kennzeichen-Unterscheidungszeichen.
 * Quelle: https://de.wikipedia.org/wiki/Liste_der_Kfz-Kennzeichen_in_Deutschland
 * (dortiger Listenstand: 1. Dezember 2023; abgerufen am 31. August 2026).
 */
export const REGIONS = {
  BW: 'Baden-Württemberg', BY: 'Bayern', BE: 'Berlin', BB: 'Brandenburg',
  HB: 'Bremen', HH: 'Hamburg', HE: 'Hessen', MV: 'Mecklenburg-Vorpommern',
  NI: 'Niedersachsen', NW: 'Nordrhein-Westfalen', RP: 'Rheinland-Pfalz',
  SL: 'Saarland', SN: 'Sachsen', ST: 'Sachsen-Anhalt', SH: 'Schleswig-Holstein',
  TH: 'Thüringen'
};

export const PLATE_CODES = [
  {"code": "A", "name": "Stadt Augsburg / Landkreis Augsburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "AA", "name": "Ostalbkreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "AB", "name": "Stadt Aschaffenburg / Landkreis Aschaffenburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ABG", "name": "Landkreis Altenburger Land", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "ABI", "name": "Landkreis Anhalt-Bitterfeld", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "AC", "name": "Städteregion Aachen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "AE", "name": "Vogtlandkreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "AH", "name": "Kreis Borken", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "AIB", "name": "Landkreis München / Landkreis Rosenheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "AIC", "name": "Landkreis Aichach-Friedberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "AK", "name": "Landkreis Altenkirchen (Westerwald)", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "ALF", "name": "Landkreis Hildesheim", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "ALZ", "name": "Landkreis Aschaffenburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "AM", "name": "Stadt Amberg", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "AN", "name": "Stadt Ansbach / Landkreis Ansbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ANA", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "ANG", "name": "Landkreis Uckermark", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "ANK", "name": "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "AÖ", "name": "Landkreis Altötting", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "AP", "name": "Landkreis Weimarer Land", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "APD", "name": "Landkreis Weimarer Land", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "ARN", "name": "Ilm-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "ART", "name": "Kyffhäuserkreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "AS", "name": "Landkreis Amberg-Sulzbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ASL", "name": "Salzlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "ASZ", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "AT", "name": "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "AU", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "AUR", "name": "Landkreis Aurich", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "AW", "name": "Landkreis Ahrweiler", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "AZ", "name": "Landkreis Alzey-Worms", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "AZE", "name": "Landkreis Anhalt-Bitterfeld", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "B", "name": "Stadt Berlin", "type": "kreisfrei", "region": "BE", "country": "DE"},
  {"code": "BA", "name": "Stadt Bamberg / Landkreis Bamberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "BAD", "name": "Stadt Baden-Baden", "type": "kreisfrei", "region": "BW", "country": "DE"},
  {"code": "BAR", "name": "Landkreis Barnim", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "BB", "name": "Landkreis Böblingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BBG", "name": "Salzlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "BC", "name": "Landkreis Biberach", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BCH", "name": "Neckar-Odenwald-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BE", "name": "Kreis Warendorf", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "BED", "name": "Landkreis Mittelsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "BEL", "name": "Landkreis Potsdam-Mittelmark", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "BER", "name": "Landkreis Barnim", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "BF", "name": "Kreis Steinfurt", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "BGD", "name": "Landkreis Berchtesgadener Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "BGL", "name": "Landkreis Berchtesgadener Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "BH", "name": "Ortenaukreis / Landkreis Rastatt", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BI", "name": "Stadt Bielefeld", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "BID", "name": "Landkreis Marburg-Biedenkopf", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "BIN", "name": "Landkreis Mainz-Bingen", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "BIR", "name": "Landkreis Birkenfeld", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "BIT", "name": "Eifelkreis Bitburg-Prüm", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "BIW", "name": "Landkreis Bautzen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "BK", "name": "Rems-Murr-Kreis / Landkreis Schwäbisch Hall / Landkreis Börde", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BKS", "name": "Landkreis Bernkastel-Wittlich", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "BL", "name": "Zollernalbkreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BLB", "name": "Kreis Siegen-Wittgenstein", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "BLK", "name": "Burgenlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "BM", "name": "Rhein-Erft-Kreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "BN", "name": "Stadt Bonn", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "BNA", "name": "Landkreis Leipzig", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "BO", "name": "Stadt Bochum", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "BÖ", "name": "Landkreis Börde", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "BOG", "name": "Landkreis Straubing-Bogen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "BOH", "name": "Kreis Borken", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "BOR", "name": "Kreis Borken", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "BOT", "name": "Stadt Bottrop", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "BR", "name": "Landkreis Karlsruhe", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BRA", "name": "Landkreis Wesermarsch", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "BRB", "name": "Stadt Brandenburg an der Havel", "type": "kreisfrei", "region": "BB", "country": "DE"},
  {"code": "BRG", "name": "Landkreis Jerichower Land", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "BRK", "name": "Landkreis Bad Kissingen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "BRL", "name": "Landkreis Goslar", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "BRV", "name": "Landkreis Rotenburg (Wümme)", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "BS", "name": "Stadt Braunschweig", "type": "kreisfrei", "region": "NI", "country": "DE"},
  {"code": "BSB", "name": "Landkreis Osnabrück", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "BSK", "name": "Landkreis Oder-Spree", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "BT", "name": "Stadt Bayreuth / Landkreis Bayreuth", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "BTF", "name": "Landkreis Anhalt-Bitterfeld", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "BÜD", "name": "Wetteraukreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "BUL", "name": "Landkreis Amberg-Sulzbach / Landkreis Schwandorf", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "BÜR", "name": "Kreis Paderborn", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "BÜS", "name": "Gemeinde Büsingen am Hochrhein (Gemeinde im Landkreis Konstanz, deutsche Exklave in der Schweiz)", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "BÜZ", "name": "Landkreis Rostock", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "BZ", "name": "Landkreis Bautzen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "C", "name": "Stadt Chemnitz", "type": "kreisfrei", "region": "SN", "country": "DE"},
  {"code": "CA", "name": "Landkreis Oberspreewald-Lausitz", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "CAS", "name": "Kreis Recklinghausen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "CB", "name": "Stadt Cottbus", "type": "kreisfrei", "region": "BB", "country": "DE"},
  {"code": "CE", "name": "Landkreis Celle", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "CHA", "name": "Landkreis Cham", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "CLP", "name": "Landkreis Cloppenburg", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "CLZ", "name": "Landkreis Goslar", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "CO", "name": "Stadt Coburg und Landkreis Coburg (→ Zweckverband Zulassungsstelle Coburg)", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "COC", "name": "Landkreis Cochem-Zell", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "COE", "name": "Kreis Coesfeld", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "CR", "name": "Landkreis Schwäbisch Hall", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "CUX", "name": "Landkreis Cuxhaven", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "CW", "name": "Landkreis Calw", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "D", "name": "Stadt Düsseldorf", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "DA", "name": "Landkreis Darmstadt-Dieburg und Stadt Darmstadt", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "DAH", "name": "Landkreis Dachau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "DAN", "name": "Landkreis Lüchow-Dannenberg", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "DAU", "name": "Landkreis Vulkaneifel", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "DBR", "name": "Landkreis Rostock", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "DD", "name": "Stadt Dresden", "type": "kreisfrei", "region": "SN", "country": "DE"},
  {"code": "DE", "name": "Stadt Dessau-Roßlau", "type": "kreisfrei", "region": "ST", "country": "DE"},
  {"code": "DEG", "name": "Landkreis Deggendorf", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "DEL", "name": "Stadt Delmenhorst", "type": "kreisfrei", "region": "NI", "country": "DE"},
  {"code": "DGF", "name": "Landkreis Dingolfing-Landau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "DH", "name": "Landkreis Diepholz", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "DI", "name": "Landkreis Darmstadt-Dieburg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "DIL", "name": "Lahn-Dill-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "DIN", "name": "Kreis Wesel", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "DIZ", "name": "Rhein-Lahn-Kreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "DKB", "name": "Landkreis Ansbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "DL", "name": "Landkreis Mittelsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "DLG", "name": "Landkreis Dillingen an der Donau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "DM", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "DN", "name": "Kreis Düren", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "DO", "name": "Stadt Dortmund", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "DON", "name": "Landkreis Donau-Ries", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "DS", "name": "Schwarzwald-Baar-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "DT", "name": "Kreis Lippe", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "DU", "name": "Stadt Duisburg", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "DUD", "name": "Landkreis Göttingen ohne die Stadt Göttingen", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "DÜW", "name": "Landkreis Bad Dürkheim", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "DW", "name": "Landkreis Sächsische Schweiz-Osterzgebirge", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "DZ", "name": "Landkreis Nordsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "E", "name": "Stadt Essen", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "EA", "name": "Wartburgkreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "EB", "name": "Landkreis Nordsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "EBE", "name": "Landkreis Ebersberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "EBN", "name": "Landkreis Haßberge", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "EBS", "name": "Landkreis Bayreuth / Landkreis Forchheim / Landkreis Kulmbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ECK", "name": "Kreis Rendsburg-Eckernförde", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "ED", "name": "Landkreis Erding", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "EE", "name": "Landkreis Elbe-Elster", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "EF", "name": "Stadt Erfurt", "type": "kreisfrei", "region": "TH", "country": "DE"},
  {"code": "EG", "name": "Landkreis Rottal-Inn", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "EH", "name": "Landkreis Oder-Spree", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "EI", "name": "Landkreis Eichstätt", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "EIC", "name": "Landkreis Eichsfeld", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "EIL", "name": "Landkreis Mansfeld-Südharz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "EIN", "name": "Landkreis Northeim", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "EIS", "name": "Saale-Holzland-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "EL", "name": "Landkreis Emsland", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "EM", "name": "Landkreis Emmendingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "EMD", "name": "Stadt Emden", "type": "kreisfrei", "region": "NI", "country": "DE"},
  {"code": "EMS", "name": "Rhein-Lahn-Kreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "EN", "name": "Ennepe-Ruhr-Kreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "ER", "name": "Stadt Erlangen", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "ERB", "name": "Odenwaldkreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "ERH", "name": "Landkreis Erlangen-Höchstadt", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ERK", "name": "Kreis Heinsberg", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "ERZ", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "ES", "name": "Landkreis Esslingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "ESB", "name": "Landkreis Amberg-Sulzbach / Landkreis Bayreuth / Landkreis Neustadt an der Waldnaab / Landkreis Nürnberger Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ESW", "name": "Werra-Meißner-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "EU", "name": "Kreis Euskirchen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "EW", "name": "Landkreis Barnim", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "F", "name": "Stadt Frankfurt am Main", "type": "kreisfrei", "region": "HE", "country": "DE"},
  {"code": "FB", "name": "Wetteraukreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "FD", "name": "Landkreis Fulda", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "FDB", "name": "Landkreis Aichach-Friedberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FDS", "name": "Landkreis Freudenstadt", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "FEU", "name": "Landkreis Ansbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FF", "name": "Stadt Frankfurt (Oder)", "type": "kreisfrei", "region": "BB", "country": "DE"},
  {"code": "FFB", "name": "Landkreis Fürstenfeldbruck", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FG", "name": "Landkreis Mittelsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "FI", "name": "Landkreis Elbe-Elster", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "FKB", "name": "Landkreis Waldeck-Frankenberg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "FL", "name": "Stadt Flensburg", "type": "kreisfrei", "region": "SH", "country": "DE"},
  {"code": "FLÖ", "name": "Landkreis Mittelsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "FN", "name": "Bodenseekreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "FO", "name": "Landkreis Forchheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FOR", "name": "Landkreis Spree-Neiße", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "FR", "name": "Stadt Freiburg im Breisgau / Landkreis Breisgau-Hochschwarzwald", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "FRG", "name": "Landkreis Freyung-Grafenau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FRI", "name": "Landkreis Friesland", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "FRW", "name": "Landkreis Märkisch-Oderland", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "FS", "name": "Landkreis Freising", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FT", "name": "Stadt Frankenthal (Pfalz)", "type": "kreisfrei", "region": "RP", "country": "DE"},
  {"code": "FTL", "name": "Landkreis Sächsische Schweiz-Osterzgebirge", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "FÜ", "name": "Stadt Fürth / Landkreis Fürth (sonst)*", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FÜS", "name": "Landkreis Ostallgäu", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "FW", "name": "Landkreis Oder-Spree", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "FZ", "name": "Schwalm-Eder-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "G", "name": "Stadt Gera", "type": "kreisfrei", "region": "TH", "country": "DE"},
  {"code": "GA", "name": "Altmarkkreis Salzwedel", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "GAN", "name": "Landkreis Northeim", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "GAP", "name": "Landkreis Garmisch-Partenkirchen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "GC", "name": "Landkreis Zwickau", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "GD", "name": "Ostalbkreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "GDB", "name": "Landkreis Nordwestmecklenburg ohne die Stadt Wismar", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "GE", "name": "Stadt Gelsenkirchen", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "GEL", "name": "Kreis Kleve", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "GEO", "name": "Landkreis Haßberge / Landkreis Schweinfurt", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "GER", "name": "Landkreis Germersheim", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "GF", "name": "Landkreis Gifhorn", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "GG", "name": "Kreis Groß-Gerau", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "GHA", "name": "Landkreis Leipzig", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "GHC", "name": "Landkreis Wittenberg", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "GI", "name": "Landkreis Gießen", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "GK", "name": "Kreis Heinsberg", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "GL", "name": "Rheinisch-Bergischer Kreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "GLA", "name": "Kreis Recklinghausen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "GM", "name": "Oberbergischer Kreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "GMN", "name": "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "GN", "name": "Main-Kinzig-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "GNT", "name": "Landkreis Jerichower Land", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "GÖ", "name": "Landkreis Göttingen Stadt Göttingen übriger Landkreis", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "GOA", "name": "Rhein-Hunsrück-Kreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "GOH", "name": "Rhein-Lahn-Kreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "GP", "name": "Landkreis Göppingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "GR", "name": "Landkreis Görlitz", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "GRA", "name": "Landkreis Freyung-Grafenau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "GRH", "name": "Landkreis Meißen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "GRI", "name": "Landkreis Rottal-Inn", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "GRM", "name": "Landkreis Leipzig", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "GRZ", "name": "Landkreis Greiz", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "GS", "name": "Landkreis Goslar", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "GT", "name": "Kreis Gütersloh", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "GTH", "name": "Landkreis Gotha", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "GÜ", "name": "Landkreis Rostock", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "GUB", "name": "Landkreis Spree-Neiße", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "GUN", "name": "Landkreis Weißenburg-Gunzenhausen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "GV", "name": "Rhein-Kreis Neuss", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "GVM", "name": "Landkreis Nordwestmecklenburg ohne die Stadt Wismar", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "GW", "name": "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "GZ", "name": "Landkreis Günzburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "H", "name": "Region Hannover Stadt Hannover übrige Region", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "HA", "name": "Stadt Hagen", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "HAB", "name": "Landkreis Bad Kissingen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "HAL", "name": "Stadt Halle (Saale)", "type": "kreisfrei", "region": "ST", "country": "DE"},
  {"code": "HAM", "name": "Stadt Hamm", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "HAS", "name": "Landkreis Haßberge", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "HB", "name": "Stadt Bremen, Senat und Bürgerschaft / Stadt Bremerhaven (X-9999)", "type": "landkreis", "region": "HB", "country": "DE"},
  {"code": "HBN", "name": "Landkreis Hildburghausen", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "HBS", "name": "Landkreis Harz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "HC", "name": "Landkreis Mittelsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "HCH", "name": "Landkreis Freudenstadt / Zollernalbkreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "HD", "name": "Stadt Heidelberg / Rhein-Neckar-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "HDH", "name": "Landkreis Heidenheim", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "HDL", "name": "Landkreis Börde", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "HE", "name": "Landkreis Helmstedt", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "HEB", "name": "Landkreis Nürnberger Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "HEF", "name": "Landkreis Hersfeld-Rotenburg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "HEI", "name": "Kreis Dithmarschen", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "HER", "name": "Stadt Herne", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "HET", "name": "Landkreis Mansfeld-Südharz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "HF", "name": "Kreis Herford", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "HG", "name": "Hochtaunuskreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "HGN", "name": "Landkreis Ludwigslust-Parchim", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "HGW", "name": "Stadt Greifswald (große kreisangehörige Stadt im Landkreis Vorpommern-Greifswald)", "type": "kreisfrei", "region": "MV", "country": "DE"},
  {"code": "HH", "name": "Freie und Hansestadt Hamburg, Senat und Bürgerschaft", "type": "landkreis", "region": "HH", "country": "DE"},
  {"code": "HHM", "name": "Burgenlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "HI", "name": "Landkreis Hildesheim", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "HIG", "name": "Landkreis Eichsfeld", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "HIP", "name": "Landkreis Roth", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "HK", "name": "Landkreis Heidekreis", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "HL", "name": "Stadt Lübeck", "type": "kreisfrei", "region": "SH", "country": "DE"},
  {"code": "HM", "name": "Landkreis Hameln-Pyrmont", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "HMÜ", "name": "Landkreis Göttingen ohne die Stadt Göttingen", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "HN", "name": "Stadt Heilbronn / Landkreis Heilbronn", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "HO", "name": "Stadt Hof / Landkreis Hof", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "HOG", "name": "Landkreis Kassel", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "HOH", "name": "Landkreis Haßberge", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "HOL", "name": "Landkreis Holzminden", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "HOM", "name": "Saarpfalz-Kreis ohne die Stadt St. Ingbert", "type": "landkreis", "region": "SL", "country": "DE"},
  {"code": "HOR", "name": "Landkreis Freudenstadt", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "HÖS", "name": "Landkreis Erlangen-Höchstadt", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "HOT", "name": "Landkreis Zwickau", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "HP", "name": "Landkreis Bergstraße", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "HR", "name": "Schwalm-Eder-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "HRO", "name": "Stadt Rostock", "type": "kreisfrei", "region": "MV", "country": "DE"},
  {"code": "HS", "name": "Kreis Heinsberg", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "HSK", "name": "Hochsauerlandkreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "HST", "name": "Stadt Stralsund (große kreisangehörige Stadt im Landkreis Vorpommern-Rügen)", "type": "kreisfrei", "region": "MV", "country": "DE"},
  {"code": "HU", "name": "Stadt Hanau / Main-Kinzig-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "HV", "name": "Landkreis Stendal", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "HVL", "name": "Landkreis Havelland", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "HWI", "name": "Stadt Wismar (große kreisangehörige Stadt im Landkreis Nordwestmecklenburg)", "type": "kreisfrei", "region": "MV", "country": "DE"},
  {"code": "HX", "name": "Kreis Höxter", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "HY", "name": "Landkreis Bautzen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "HZ", "name": "Landkreis Harz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "IGB", "name": "Stadt St. Ingbert (Mittelstadt im Saarpfalz-Kreis)", "type": "kreisfrei", "region": "SL", "country": "DE"},
  {"code": "IK", "name": "Ilm-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "IL", "name": "Ilm-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "ILL", "name": "Landkreis Neu-Ulm", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "IN", "name": "Stadt Ingolstadt", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "IZ", "name": "Kreis Steinburg", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "J", "name": "Stadt Jena", "type": "kreisfrei", "region": "TH", "country": "DE"},
  {"code": "JB", "name": "Landkreis Teltow-Fläming", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "JE", "name": "Landkreis Wittenberg", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "JL", "name": "Landkreis Jerichower Land", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "JÜL", "name": "Kreis Düren", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "K", "name": "Stadt Köln", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "KA", "name": "Stadt Karlsruhe / Landkreis Karlsruhe", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "KB", "name": "Landkreis Waldeck-Frankenberg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "KC", "name": "Landkreis Kronach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KE", "name": "Stadt Kempten (Allgäu)", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "KEH", "name": "Landkreis Kelheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KEL", "name": "Ortenaukreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "KEM", "name": "Landkreis Bayreuth / Landkreis Tirschenreuth", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KF", "name": "Stadt Kaufbeuren", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "KG", "name": "Landkreis Bad Kissingen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KH", "name": "Landkreis Bad Kreuznach", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "KI", "name": "Stadt Kiel", "type": "kreisfrei", "region": "SH", "country": "DE"},
  {"code": "KIB", "name": "Donnersbergkreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "KK", "name": "Kreis Viersen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "KL", "name": "Stadt Kaiserslautern / Landkreis Kaiserslautern", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "KLE", "name": "Kreis Kleve", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "KLZ", "name": "Altmarkkreis Salzwedel", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "KM", "name": "Landkreis Bautzen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "KN", "name": "Landkreis Konstanz ohne die Gemeinde Büsingen am Hochrhein", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "KO", "name": "Stadt Koblenz", "type": "kreisfrei", "region": "RP", "country": "DE"},
  {"code": "KÖN", "name": "Landkreis Rhön-Grabfeld", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KÖT", "name": "Landkreis Anhalt-Bitterfeld", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "KÖZ", "name": "Landkreis Cham", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KR", "name": "Stadt Krefeld", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "KRU", "name": "Landkreis Günzburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KS", "name": "Landkreis Kassel und Stadt Kassel", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "KT", "name": "Landkreis Kitzingen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KU", "name": "Landkreis Kulmbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "KÜN", "name": "Hohenlohekreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "KUS", "name": "Landkreis Kusel", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "KW", "name": "Landkreis Dahme-Spreewald", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "KY", "name": "Landkreis Ostprignitz-Ruppin", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "KYF", "name": "Kyffhäuserkreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "L", "name": "Stadt Leipzig / Landkreis Leipzig", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "LA", "name": "Stadt Landshut / Landkreis Landshut", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "LAN", "name": "Landkreis Dingolfing-Landau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "LAU", "name": "Landkreis Nürnberger Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "LB", "name": "Landkreis Ludwigsburg", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "LBS", "name": "Saale-Orla-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "LBZ", "name": "Landkreis Ludwigslust-Parchim", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "LC", "name": "Landkreis Dahme-Spreewald", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "LD", "name": "Stadt Landau in der Pfalz", "type": "kreisfrei", "region": "RP", "country": "DE"},
  {"code": "LDK", "name": "Lahn-Dill-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "LDS", "name": "Landkreis Dahme-Spreewald", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "LE", "name": "Kreis Lippe", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "LEO", "name": "Landkreis Böblingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "LER", "name": "Landkreis Leer", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "LEV", "name": "Stadt Leverkusen", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "LF", "name": "Landkreis Altötting / Landkreis Berchtesgadener Land / Landkreis Traunstein", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "LG", "name": "Landkreis Lüneburg", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "LH", "name": "Kreis Coesfeld / Kreis Unna", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "LI", "name": "Landkreis Lindau (Bodensee)", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "LIB", "name": "Landkreis Elbe-Elster", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "LIF", "name": "Landkreis Lichtenfels", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "LIP", "name": "Kreis Lippe", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "LK", "name": "Kreis Minden-Lübbecke", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "LL", "name": "Landkreis Landsberg am Lech", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "LM", "name": "Landkreis Limburg-Weilburg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "LN", "name": "Landkreis Dahme-Spreewald", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "LÖ", "name": "Landkreis Lörrach", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "LÖB", "name": "Landkreis Görlitz", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "LOS", "name": "Landkreis Oder-Spree", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "LP", "name": "Kreis Soest", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "LR", "name": "Ortenaukreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "LRO", "name": "Landkreis Rostock", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "LSZ", "name": "Unstrut-Hainich-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "LU", "name": "Stadt Ludwigshafen am Rhein", "type": "kreisfrei", "region": "RP", "country": "DE"},
  {"code": "LUK", "name": "Landkreis Teltow-Fläming", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "LÜN", "name": "Kreis Unna", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "LUP", "name": "Landkreis Ludwigslust-Parchim", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "LWL", "name": "Landkreis Ludwigslust-Parchim", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "M", "name": "Stadt München / Landkreis München", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MA", "name": "Stadt Mannheim", "type": "kreisfrei", "region": "BW", "country": "DE"},
  {"code": "MAB", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "MAI", "name": "Landkreis Kelheim / Landkreis Landshut", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MAK", "name": "Landkreis Wunsiedel im Fichtelgebirge", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MAL", "name": "Landkreis Landshut / Landkreis Straubing-Bogen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MB", "name": "Landkreis Miesbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MC", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "MD", "name": "Stadt Magdeburg", "type": "kreisfrei", "region": "ST", "country": "DE"},
  {"code": "ME", "name": "Kreis Mettmann", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "MED", "name": "Kreis Dithmarschen", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "MEG", "name": "Schwalm-Eder-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "MEI", "name": "Landkreis Meißen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "MEK", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "MEL", "name": "Landkreis Osnabrück", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "MER", "name": "Saalekreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "MET", "name": "Landkreis Rhön-Grabfeld", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MG", "name": "Stadt Mönchengladbach", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "MGH", "name": "Main-Tauber-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "MGN", "name": "Landkreis Schmalkalden-Meiningen", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "MH", "name": "Stadt Mülheim an der Ruhr", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "MHL", "name": "Unstrut-Hainich-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "MI", "name": "Kreis Minden-Lübbecke", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "MIL", "name": "Landkreis Miltenberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MK", "name": "Märkischer Kreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "MKK", "name": "Main-Kinzig-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "ML", "name": "Landkreis Mansfeld-Südharz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "MM", "name": "Stadt Memmingen", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "MN", "name": "Landkreis Unterallgäu", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MO", "name": "Kreis Wesel", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "MOD", "name": "Landkreis Ostallgäu", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MOL", "name": "Landkreis Märkisch-Oderland", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "MON", "name": "Städteregion Aachen / Kreis Düren", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "MOS", "name": "Neckar-Odenwald-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "MQ", "name": "Saalekreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "MR", "name": "Landkreis Marburg-Biedenkopf", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "MS", "name": "Stadt Münster", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "MSE", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "MSH", "name": "Landkreis Mansfeld-Südharz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "MSP", "name": "Landkreis Main-Spessart", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MST", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "MTK", "name": "Main-Taunus-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "MTL", "name": "Landkreis Leipzig", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "MU", "name": "Landkreis München", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MÜ", "name": "Landkreis Mühldorf am Inn", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MÜB", "name": "Landkreis Bayreuth / Landkreis Hof", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "MUC", "name": "Stadt München", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "MÜL", "name": "Landkreis Breisgau-Hochschwarzwald", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "MÜR", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "MW", "name": "Landkreis Mittelsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "MY", "name": "Landkreis Mayen-Koblenz", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "MYK", "name": "Landkreis Mayen-Koblenz", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "MZ", "name": "Stadt Mainz / Landkreis Mainz-Bingen", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "MZG", "name": "Landkreis Merzig-Wadern", "type": "landkreis", "region": "SL", "country": "DE"},
  {"code": "N", "name": "Stadt Nürnberg / Landkreis Nürnberger Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NAB", "name": "Landkreis Amberg-Sulzbach / Landkreis Schwandorf", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NAI", "name": "Landkreis Hof", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NAU", "name": "Landkreis Havelland", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "NB", "name": "Stadt Neubrandenburg (große kreisangehörige Stadt im Landkreis Mecklenburgische Seenplatte)", "type": "kreisfrei", "region": "MV", "country": "DE"},
  {"code": "ND", "name": "Landkreis Neuburg-Schrobenhausen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NDH", "name": "Landkreis Nordhausen", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "NE", "name": "Rhein-Kreis Neuss", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "NEA", "name": "Landkreis Neustadt an der Aisch-Bad Windsheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NEB", "name": "Burgenlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "NEC", "name": "Stadt Coburg und Landkreis Coburg (→ Zweckverband Zulassungsstelle Coburg)", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "NEN", "name": "Landkreis Schwandorf", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NES", "name": "Landkreis Rhön-Grabfeld", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NEU", "name": "Landkreis Breisgau-Hochschwarzwald", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "NEW", "name": "Landkreis Neustadt an der Waldnaab", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NF", "name": "Kreis Nordfriesland", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "NH", "name": "Landkreis Sonneberg", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "NI", "name": "Landkreis Nienburg/Weser", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "NK", "name": "Landkreis Neunkirchen", "type": "landkreis", "region": "SL", "country": "DE"},
  {"code": "NM", "name": "Landkreis Neumarkt in der Oberpfalz", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NMB", "name": "Burgenlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "NMS", "name": "Stadt Neumünster", "type": "kreisfrei", "region": "SH", "country": "DE"},
  {"code": "NÖ", "name": "Landkreis Donau-Ries", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NOH", "name": "Landkreis Grafschaft Bentheim", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "NOL", "name": "Landkreis Görlitz", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "NOM", "name": "Landkreis Northeim", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "NOR", "name": "Landkreis Aurich", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "NP", "name": "Landkreis Ostprignitz-Ruppin", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "NR", "name": "Landkreis Neuwied", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "NT", "name": "Landkreis Esslingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "NU", "name": "Landkreis Neu-Ulm", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "NVP", "name": "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "NW", "name": "Stadt Neustadt an der Weinstraße", "type": "kreisfrei", "region": "RP", "country": "DE"},
  {"code": "NWM", "name": "Landkreis Nordwestmecklenburg ohne die Stadt Wismar", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "NY", "name": "Landkreis Görlitz", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "NZ", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "OA", "name": "Landkreis Oberallgäu", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "OAL", "name": "Landkreis Ostallgäu", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "OB", "name": "Stadt Oberhausen", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "OBB", "name": "Landkreis Miltenberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "OBG", "name": "Landkreis Stendal", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "OC", "name": "Landkreis Börde", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "OCH", "name": "Landkreis Würzburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "OD", "name": "Kreis Stormarn", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "OE", "name": "Kreis Olpe", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "OF", "name": "Landkreis Offenbach und Stadt Offenbach am Main", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "OG", "name": "Ortenaukreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "OH", "name": "Kreis Ostholstein", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "OHA", "name": "Landkreis Göttingen ohne die Stadt Göttingen", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "ÖHR", "name": "Hohenlohekreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "OHV", "name": "Landkreis Oberhavel", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "OHZ", "name": "Landkreis Osterholz", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "OK", "name": "Landkreis Börde", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "OL", "name": "Stadt Oldenburg / Landkreis Oldenburg", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "OP", "name": "Stadt Leverkusen", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "OPR", "name": "Landkreis Ostprignitz-Ruppin", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "OS", "name": "Stadt Osnabrück / Landkreis Osnabrück", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "OSL", "name": "Landkreis Oberspreewald-Lausitz", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "OTW", "name": "Landkreis Neunkirchen", "type": "landkreis", "region": "SL", "country": "DE"},
  {"code": "OVI", "name": "Landkreis Schwandorf", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "OVL", "name": "Vogtlandkreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "OZ", "name": "Landkreis Nordsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "P", "name": "Stadt Potsdam", "type": "kreisfrei", "region": "BB", "country": "DE"},
  {"code": "PA", "name": "Stadt Passau / Landkreis Passau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "PAF", "name": "Landkreis Pfaffenhofen an der Ilm", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "PAN", "name": "Landkreis Rottal-Inn", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "PAR", "name": "Landkreis Kelheim / Landkreis Neumarkt in der Oberpfalz", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "PB", "name": "Kreis Paderborn", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "PCH", "name": "Landkreis Ludwigslust-Parchim", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "PE", "name": "Landkreis Peine", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "PEG", "name": "Landkreis Bayreuth / Landkreis Forchheim / Landkreis Nürnberger Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "PF", "name": "Stadt Pforzheim / Enzkreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "PI", "name": "Kreis Pinneberg", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "PIR", "name": "Landkreis Sächsische Schweiz-Osterzgebirge", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "PL", "name": "Vogtlandkreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "PLÖ", "name": "Kreis Plön", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "PM", "name": "Landkreis Potsdam-Mittelmark", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "PN", "name": "Saale-Orla-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "PR", "name": "Landkreis Prignitz", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "PRÜ", "name": "Eifelkreis Bitburg-Prüm", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "PS", "name": "Stadt Pirmasens / Landkreis Südwestpfalz", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "PW", "name": "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "PZ", "name": "Landkreis Uckermark", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "QFT", "name": "Saalekreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "QLB", "name": "Landkreis Harz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "R", "name": "Stadt Regensburg / Landkreis Regensburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "RA", "name": "Landkreis Rastatt", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "RC", "name": "Vogtlandkreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "RD", "name": "Kreis Rendsburg-Eckernförde", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "RDG", "name": "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "RE", "name": "Kreis Recklinghausen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "REG", "name": "Landkreis Regen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "REH", "name": "Landkreis Hof / Landkreis Wunsiedel im Fichtelgebirge", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "REI", "name": "Landkreis Berchtesgadener Land", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "RG", "name": "Landkreis Meißen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "RH", "name": "Landkreis Roth", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "RI", "name": "Landkreis Schaumburg", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "RID", "name": "Landkreis Kelheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "RIE", "name": "Landkreis Meißen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "RL", "name": "Landkreis Mittelsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "RM", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "RN", "name": "Landkreis Havelland", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "RO", "name": "Stadt Rosenheim / Landkreis Rosenheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ROD", "name": "Landkreis Cham / Landkreis Schwandorf", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ROF", "name": "Landkreis Hersfeld-Rotenburg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "ROK", "name": "Donnersbergkreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "ROL", "name": "Landkreis Kelheim / Landkreis Landshut", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ROS", "name": "Landkreis Rostock", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "ROT", "name": "Landkreis Ansbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "ROW", "name": "Landkreis Rotenburg (Wümme)", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "RP", "name": "Rhein-Pfalz-Kreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "RS", "name": "Stadt Remscheid", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "RSL", "name": "Stadt Dessau-Roßlau", "type": "kreisfrei", "region": "ST", "country": "DE"},
  {"code": "RT", "name": "Landkreis Reutlingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "RU", "name": "Landkreis Saalfeld-Rudolstadt", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "RÜD", "name": "Rheingau-Taunus-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "RÜG", "name": "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "RV", "name": "Landkreis Ravensburg", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "RW", "name": "Landkreis Rottweil", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "RZ", "name": "Kreis Herzogtum Lauenburg", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "S", "name": "Stadt Stuttgart", "type": "kreisfrei", "region": "BW", "country": "DE"},
  {"code": "SAB", "name": "Landkreis Trier-Saarburg", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "SAD", "name": "Landkreis Schwandorf", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SÄK", "name": "Landkreis Waldshut", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "SAN", "name": "Landkreis Hof / Landkreis Kronach / Landkreis Kulmbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SAW", "name": "Altmarkkreis Salzwedel", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "SB", "name": "Regionalverband Saarbrücken ohne die Stadt Völklingen", "type": "landkreis", "region": "SL", "country": "DE"},
  {"code": "SBG", "name": "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "SBK", "name": "Salzlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "SC", "name": "Stadt Schwabach", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "SCZ", "name": "Saale-Orla-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SDH", "name": "Kyffhäuserkreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SDL", "name": "Landkreis Stendal", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "SDT", "name": "Landkreis Uckermark", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "SE", "name": "Kreis Segeberg", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "SEB", "name": "Landkreis Sächsische Schweiz-Osterzgebirge", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "SEE", "name": "Landkreis Märkisch-Oderland", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "SEF", "name": "Landkreis Neustadt an der Aisch-Bad Windsheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SEL", "name": "Landkreis Wunsiedel im Fichtelgebirge", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SFB", "name": "Landkreis Oberspreewald-Lausitz", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "SFT", "name": "Salzlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "SG", "name": "Stadt Solingen", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "SGH", "name": "Landkreis Mansfeld-Südharz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "SHA", "name": "Landkreis Schwäbisch Hall", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "SHG", "name": "Landkreis Schaumburg", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "SHK", "name": "Saale-Holzland-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SHL", "name": "Stadt Suhl", "type": "kreisfrei", "region": "TH", "country": "DE"},
  {"code": "SI", "name": "Kreis Siegen-Wittgenstein", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "SIG", "name": "Landkreis Sigmaringen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "SIM", "name": "Rhein-Hunsrück-Kreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "SK", "name": "Saalekreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "SL", "name": "Kreis Schleswig-Flensburg", "type": "landkreis", "region": "SH", "country": "DE"},
  {"code": "SLE", "name": "Kreis Düren / Kreis Euskirchen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "SLF", "name": "Landkreis Saalfeld-Rudolstadt", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SLG", "name": "Landkreis Ravensburg / Landkreis Sigmaringen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "SLK", "name": "Salzlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "SLN", "name": "Landkreis Altenburger Land", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SLS", "name": "Landkreis Saarlouis", "type": "landkreis", "region": "SL", "country": "DE"},
  {"code": "SLÜ", "name": "Main-Kinzig-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "SLZ", "name": "Wartburgkreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SM", "name": "Landkreis Schmalkalden-Meiningen", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SMÜ", "name": "Landkreis Augsburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SN", "name": "Stadt Schwerin", "type": "kreisfrei", "region": "MV", "country": "DE"},
  {"code": "SO", "name": "Kreis Soest", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "SOB", "name": "Landkreis Neuburg-Schrobenhausen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SOG", "name": "Landkreis Weilheim-Schongau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SOK", "name": "Saale-Orla-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SÖM", "name": "Landkreis Sömmerda", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SON", "name": "Landkreis Sonneberg", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "SP", "name": "Stadt Speyer", "type": "kreisfrei", "region": "RP", "country": "DE"},
  {"code": "SPB", "name": "Landkreis Spree-Neiße", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "SPN", "name": "Landkreis Spree-Neiße", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "SR", "name": "Landkreis Straubing-Bogen / Stadt Straubing", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SRB", "name": "Landkreis Märkisch-Oderland", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "SRO", "name": "Saale-Holzland-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "ST", "name": "Kreis Steinfurt", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "STA", "name": "Landkreis Starnberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "STB", "name": "Landkreis Ludwigslust-Parchim", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "STD", "name": "Landkreis Stade", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "STE", "name": "Landkreis Lichtenfels", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "STL", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "STO", "name": "Landkreis Konstanz / Landkreis Sigmaringen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "SU", "name": "Rhein-Sieg-Kreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "SUL", "name": "Landkreis Amberg-Sulzbach", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SÜW", "name": "Landkreis Südliche Weinstraße", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "SW", "name": "Stadt Schweinfurt / Landkreis Schweinfurt", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "SWA", "name": "Rheingau-Taunus-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "SY", "name": "Landkreis Diepholz", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "SZ", "name": "Stadt Salzgitter", "type": "kreisfrei", "region": "NI", "country": "DE"},
  {"code": "SZB", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "TBB", "name": "Main-Tauber-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "TDO", "name": "Landkreis Nordsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "TE", "name": "Kreis Steinfurt", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "TET", "name": "Landkreis Rostock", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "TF", "name": "Landkreis Teltow-Fläming", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "TG", "name": "Landkreis Nordsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "TIR", "name": "Landkreis Tirschenreuth", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "TO", "name": "Landkreis Nordsachsen", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "TÖL", "name": "Landkreis Bad Tölz-Wolfratshausen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "TP", "name": "Landkreis Uckermark", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "TR", "name": "Landkreis Trier-Saarburg und Stadt Trier", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "TS", "name": "Landkreis Traunstein", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "TT", "name": "Bodenseekreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "TÜ", "name": "Landkreis Tübingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "TUT", "name": "Landkreis Tuttlingen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "ÜB", "name": "Bodenseekreis / Landkreis Ravensburg / Landkreis Sigmaringen", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "UE", "name": "Landkreis Uelzen", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "UEM", "name": "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "UFF", "name": "Landkreis Neustadt an der Aisch-Bad Windsheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "UH", "name": "Unstrut-Hainich-Kreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "UL", "name": "Stadt Ulm / Alb-Donau-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "UM", "name": "Landkreis Uckermark", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "UN", "name": "Kreis Unna", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "USI", "name": "Hochtaunuskreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "V", "name": "Vogtlandkreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "VAI", "name": "Landkreis Ludwigsburg", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "VB", "name": "Vogelsbergkreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "VEC", "name": "Landkreis Vechta", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "VER", "name": "Landkreis Verden", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "VG", "name": "Landkreis Vorpommern-Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "VIB", "name": "Landkreis Landshut / Landkreis Mühldorf a.Inn / Landkreis Rottal-Inn", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "VIE", "name": "Kreis Viersen", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "VIT", "name": "Landkreis Regen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "VK", "name": "Stadt Völklingen (Mittelstadt im Regionalverband Saarbrücken)", "type": "kreisfrei", "region": "SL", "country": "DE"},
  {"code": "VOH", "name": "Landkreis Neustadt an der Waldnaab", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "VR", "name": "Landkreis Vorpommern-Rügen ohne die Stadt Stralsund", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "VS", "name": "Schwarzwald-Baar-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "W", "name": "Stadt Wuppertal", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "WA", "name": "Landkreis Waldeck-Frankenberg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "WAF", "name": "Kreis Warendorf", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "WAK", "name": "Wartburgkreis", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "WAN", "name": "Stadt Herne", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "WAR", "name": "Kreis Höxter", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "WAT", "name": "Stadt Bochum", "type": "kreisfrei", "region": "NW", "country": "DE"},
  {"code": "WB", "name": "Landkreis Wittenberg", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "WBS", "name": "Landkreis Eichsfeld", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "WDA", "name": "Landkreis Zwickau", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "WE", "name": "Stadt Weimar", "type": "kreisfrei", "region": "TH", "country": "DE"},
  {"code": "WEL", "name": "Landkreis Limburg-Weilburg", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "WEN", "name": "Stadt Weiden in der Oberpfalz", "type": "kreisfrei", "region": "BY", "country": "DE"},
  {"code": "WER", "name": "Landkreis Augsburg / Landkreis Dillingen an der Donau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WES", "name": "Kreis Wesel", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "WF", "name": "Landkreis Wolfenbüttel", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "WG", "name": "Landkreis Ravensburg", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "WHV", "name": "Stadt Wilhelmshaven", "type": "kreisfrei", "region": "NI", "country": "DE"},
  {"code": "WI", "name": "Stadt Wiesbaden", "type": "kreisfrei", "region": "HE", "country": "DE"},
  {"code": "WIL", "name": "Landkreis Bernkastel-Wittlich", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "WIS", "name": "Landkreis Nordwestmecklenburg ohne die Stadt Wismar", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "WIT", "name": "Ennepe-Ruhr-Kreis", "type": "landkreis", "region": "NW", "country": "DE"},
  {"code": "WIZ", "name": "Werra-Meißner-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "WK", "name": "Landkreis Ostprignitz-Ruppin", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "WL", "name": "Landkreis Harburg", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "WLG", "name": "Landkreis Vorpommern-Greifswald ohne die Stadt Greifswald", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "WM", "name": "Landkreis Weilheim-Schongau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WMS", "name": "Landkreis Börde", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "WN", "name": "Rems-Murr-Kreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "WND", "name": "Landkreis St. Wendel", "type": "landkreis", "region": "SL", "country": "DE"},
  {"code": "WO", "name": "Stadt Worms", "type": "kreisfrei", "region": "RP", "country": "DE"},
  {"code": "WOB", "name": "Stadt Wolfsburg", "type": "kreisfrei", "region": "NI", "country": "DE"},
  {"code": "WOH", "name": "Landkreis Kassel", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "WOL", "name": "Landkreis Freudenstadt / Ortenaukreis", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "WOR", "name": "Landkreis Bad Tölz-Wolfratshausen / Landkreis München / Landkreis Starnberg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WOS", "name": "Landkreis Freyung-Grafenau", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WR", "name": "Landkreis Harz", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "WRN", "name": "Landkreis Mecklenburgische Seenplatte ohne die Stadt Neubrandenburg", "type": "landkreis", "region": "MV", "country": "DE"},
  {"code": "WS", "name": "Landkreis Mühldorf a.Inn / Landkreis Rosenheim", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WSF", "name": "Burgenlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "WST", "name": "Landkreis Ammerland", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "WSW", "name": "Landkreis Görlitz", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "WT", "name": "Landkreis Waldshut", "type": "landkreis", "region": "BW", "country": "DE"},
  {"code": "WTL", "name": "Landkreis Osnabrück", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "WTM", "name": "Landkreis Wittmund", "type": "landkreis", "region": "NI", "country": "DE"},
  {"code": "WÜ", "name": "Stadt Würzburg / Landkreis Würzburg", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WUG", "name": "Landkreis Weißenburg-Gunzenhausen", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WÜM", "name": "Landkreis Cham", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WUN", "name": "Landkreis Wunsiedel im Fichtelgebirge", "type": "landkreis", "region": "BY", "country": "DE"},
  {"code": "WUR", "name": "Landkreis Leipzig", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "WW", "name": "Westerwaldkreis", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "WZ", "name": "Lahn-Dill-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "WZL", "name": "Landkreis Börde", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "Z", "name": "Landkreis Zwickau", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "ZE", "name": "Landkreis Anhalt-Bitterfeld", "type": "landkreis", "region": "ST", "country": "DE"},
  {"code": "ZEL", "name": "Landkreis Cochem-Zell", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "ZI", "name": "Landkreis Görlitz", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "ZIG", "name": "Schwalm-Eder-Kreis", "type": "landkreis", "region": "HE", "country": "DE"},
  {"code": "ZP", "name": "Erzgebirgskreis", "type": "landkreis", "region": "SN", "country": "DE"},
  {"code": "ZR", "name": "Landkreis Greiz", "type": "landkreis", "region": "TH", "country": "DE"},
  {"code": "ZS", "name": "Landkreis Teltow-Fläming", "type": "landkreis", "region": "BB", "country": "DE"},
  {"code": "ZW", "name": "Stadt Zweibrücken / Landkreis Südwestpfalz", "type": "landkreis", "region": "RP", "country": "DE"},
  {"code": "ZZ", "name": "Burgenlandkreis", "type": "landkreis", "region": "ST", "country": "DE"},
];
