/**
 * Aktuelle deutsche Kfz-Kennzeichen-Unterscheidungszeichen.
 * Quelle: https://de.wikipedia.org/wiki/Liste_der_Kfz-Kennzeichen_in_Deutschland
 * (dortiger Listenstand: 1. Dezember 2023; abgerufen am 31. August 2026).
 */
export const REGIONS = {
  BW: 'Baden-Württemberg', BY: 'Bayern', BE: 'Berlin', BB: 'Brandenburg',
  HB: 'Bremen', HH: 'Hamburg', HE: 'Hessen', MV: 'Mecklenburg-Vorpommern',
  NI: 'Niedersachsen', NW: 'Nordrhein-Westfalen', RP: 'Rheinland-Pfalz',
  SL: 'Saarland', SN: 'Sachsen', ST: 'Sachsen-Anhalt', SH: 'Schleswig-Holstein',
  TH: 'Thüringen'
};

export const PLATE_CODES = [
  {"code": "A", "name": "Augsburg", "region": "BY", "country": "DE"},
  {"code": "AA", "name": "Ostalbkreis (Aalen)", "region": "BW", "country": "DE"},
  {"code": "AB", "name": "Aschaffenburg", "region": "BY", "country": "DE"},
  {"code": "ABG", "name": "Altenburger Land", "region": "TH", "country": "DE"},
  {"code": "ABI", "name": "Anhalt-Bitterfeld", "region": "ST", "country": "DE"},
  {"code": "AC", "name": "Aachen", "region": "NRW", "country": "DE"},
  {"code": "AE", "name": "Auerbach", "region": "SN", "country": "DE"},
  {"code": "AH", "name": "Ahaus", "region": "NRW", "country": "DE"},
  {"code": "AIB", "name": "Bad Aibling", "region": "BY", "country": "DE"},
  {"code": "AIC", "name": "Aichach-Friedberg", "region": "BY", "country": "DE"},
  {"code": "AK", "name": "Altenkirchen", "region": "RP", "country": "DE"},
  {"code": "AL", "name": "Kreis Altena", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "MK"},
  {"code": "ALF", "name": "Alfeld (Leine)", "region": "NI", "country": "DE"},
  {"code": "ALS", "name": "Alsfeld", "region": "HE", "country": "DE", "isDeprecated": true, "currentCode": "VB"},
  {"code": "ALZ", "name": "Alzenau", "region": "BY", "country": "DE"},
  {"code": "AM", "name": "Amberg", "region": "BY", "country": "DE"},
  {"code": "AN", "name": "Ansbach", "region": "BY", "country": "DE"},
  {"code": "ANA", "name": "Annaberg", "region": "SN", "country": "DE"},
  {"code": "ANG", "name": "Angermünde", "region": "BB", "country": "DE"},
  {"code": "ANK", "name": "Anklam", "region": "MV", "country": "DE"},
  {"code": "AÖ", "name": "Altötting", "region": "BY", "country": "DE"},
  {"code": "AP", "name": "Weimarer Land (Apolda)", "region": "TH", "country": "DE"},
  {"code": "APD", "name": "Apolda", "region": "TH", "country": "DE"},
  {"code": "AR", "name": "Arnsberg", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "HSK"},
  {"code": "ARN", "name": "Arnstadt", "region": "TH", "country": "DE"},
  {"code": "ART", "name": "Artern", "region": "TH", "country": "DE"},
  {"code": "ASD", "name": "Aschendorf-Hümmling", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "EL"},
  {"code": "AS", "name": "Amberg-Sulzbach", "region": "BY", "country": "DE"},
  {"code": "ASL", "name": "Aschersleben-Staßfurt", "region": "ST", "country": "DE"},
  {"code": "ASZ", "name": "Aue-Schwarzenberg", "region": "SN", "country": "DE"},
  {"code": "AT", "name": "Altentreptow", "region": "MV", "country": "DE"},
  {"code": "AU", "name": "Aue", "region": "SN", "country": "DE"},
  {"code": "AUR", "name": "Aurich", "region": "NI", "country": "DE"},
  {"code": "AW", "name": "Ahrweiler", "region": "RP", "country": "DE"},
  {"code": "AZ", "name": "Alzey-Worms", "region": "RP", "country": "DE"},
  {"code": "AZE", "name": "Anhalt-Zerbst", "region": "ST", "country": "DE"},
  {"code": "B", "name": "Berlin", "region": "BE", "country": "DE"},
  {"code": "BA", "name": "Bamberg", "region": "BY", "country": "DE"},
  {"code": "BAD", "name": "Baden-Baden", "region": "BW", "country": "DE"},
  {"code": "BAR", "name": "Landkreis Barnim", "region": "BB", "country": "DE"},
  {"code": "BB", "name": "Böblingen", "region": "BW", "country": "DE"},
  {"code": "BBG", "name": "Bernburg", "region": "ST", "country": "DE"},
  {"code": "BC", "name": "Biberach", "region": "BW", "country": "DE"},
  {"code": "BCH", "name": "Buchen (Odenwald)", "region": "BW", "country": "DE"},
  {"code": "BE", "name": "Beckum", "region": "NRW", "country": "DE"},
  {"code": "BED", "name": "Brand-Erbisdorf", "region": "SN", "country": "DE"},
  {"code": "BEI", "name": "Beilngries", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "EI"},
  {"code": "BEL", "name": "Belzig", "region": "BB", "country": "DE"},
  {"code": "BER", "name": "Bernau", "region": "BB", "country": "DE"},
  {"code": "BF", "name": "Burgsteinfurt", "region": "NRW", "country": "DE"},
  {"code": "BGD", "name": "Berchtesgaden", "region": "BY", "country": "DE"},
  {"code": "BGL", "name": "Berchtesgadener Land", "region": "BY", "country": "DE"},
  {"code": "BH", "name": "Bühl", "region": "BW", "country": "DE"},
  {"code": "BI", "name": "Bielefeld", "region": "NRW", "country": "DE"},
  {"code": "BID", "name": "Biedenkopf", "region": "HE", "country": "DE"},
  {"code": "BIN", "name": "Bingen am Rhein", "region": "RP", "country": "DE"},
  {"code": "BIR", "name": "Birkenfeld", "region": "RP", "country": "DE"},
  {"code": "BIT", "name": "Bitburg-Prüm (Eifelkreis)", "region": "RP", "country": "DE"},
  {"code": "BIW", "name": "Bischofswerda", "region": "SN", "country": "DE"},
  {"code": "BK", "name": "Backnang", "region": "BW", "country": "DE"},
  {"code": "BK", "name": "Landkreis Börde", "region": "ST", "country": "DE"},
  {"code": "BKS", "name": "Bernkastel-Kues", "region": "RP", "country": "DE"},
  {"code": "BL", "name": "Zollernalbkreis (Balingen)", "region": "BW", "country": "DE"},
  {"code": "BLB", "name": "Berleburg", "region": "NRW", "country": "DE"},
  {"code": "BLK", "name": "Burgenlandkreis", "region": "ST", "country": "DE"},
  {"code": "BM", "name": "Rhein-Erft-Kreis (Bergheim)", "region": "NRW", "country": "DE"},
  {"code": "BN", "name": "Bonn", "region": "NRW", "country": "DE"},
  {"code": "BNA", "name": "Borna", "region": "SN", "country": "DE"},
  {"code": "BO", "name": "Bochum", "region": "NRW", "country": "DE"},
  {"code": "BÖ", "name": "Bördekreis", "region": "ST", "country": "DE"},
  {"code": "BOG", "name": "Bogen", "region": "BY", "country": "DE"},
  {"code": "BOH", "name": "Bocholt", "region": "NRW", "country": "DE"},
  {"code": "BOR", "name": "Borken", "region": "NRW", "country": "DE"},
  {"code": "BOT", "name": "Bottrop", "region": "NRW", "country": "DE"},
  {"code": "BR", "name": "Bruchsal", "region": "BW", "country": "DE"},
  {"code": "BRA", "name": "Wesermarsch (Brake)", "region": "NI", "country": "DE"},
  {"code": "BRB", "name": "Brandenburg", "region": "BB", "country": "DE"},
  {"code": "BRG", "name": "Burg", "region": "ST", "country": "DE"},
  {"code": "BRI", "name": "Brilon", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "HSK"},
  {"code": "BRK", "name": "Bad Brückenau", "region": "BY", "country": "DE"},
  {"code": "BRL", "name": "Blankenburg (Braunlage)", "region": "NI", "country": "DE"},
  {"code": "BRV", "name": "Bremervörde", "region": "NI", "country": "DE"},
  {"code": "BS", "name": "Braunschweig", "region": "NI", "country": "DE"},
  {"code": "BSB", "name": "Bersenbrück", "region": "NI", "country": "DE"},
  {"code": "BSK", "name": "Beeskow", "region": "BB", "country": "DE"},
  {"code": "BT", "name": "Bayreuth", "region": "BY", "country": "DE"},
  {"code": "BTF", "name": "Bitterfeld", "region": "ST", "country": "DE"},
  {"code": "BU", "name": "Burgdorf", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "H"},
  {"code": "BÜD", "name": "Büdingen", "region": "HE", "country": "DE"},
  {"code": "BÜR", "name": "Büren", "region": "NRW", "country": "DE"},
  {"code": "BÜS", "name": "Büsingen (Konstanz)", "region": "BW", "country": "DE"},
  {"code": "BÜZ", "name": "Bützow", "region": "MV", "country": "DE"},
  {"code": "BUL", "name": "Burglengenfeld", "region": "BY", "country": "DE"},
  {"code": "BZ", "name": "Bautzen", "region": "SN", "country": "DE"},
  {"code": "BZA", "name": "Bergzabern", "region": "RP", "country": "DE", "isDeprecated": true, "currentCode": "SÜW"},
  {"code": "C", "name": "Chemnitz", "region": "SN", "country": "DE"},
  {"code": "CA", "name": "Calau", "region": "BB", "country": "DE"},
  {"code": "CAS", "name": "Castrop-Rauxel", "region": "NRW", "country": "DE"},
  {"code": "CB", "name": "Cottbus", "region": "BB", "country": "DE"},
  {"code": "CE", "name": "Celle", "region": "NI", "country": "DE"},
  {"code": "CHA", "name": "Cham", "region": "BY", "country": "DE"},
  {"code": "CLP", "name": "Cloppenburg", "region": "NI", "country": "DE"},
  {"code": "CLZ", "name": "Clausthal-Zellerfeld", "region": "NI", "country": "DE"},
  {"code": "CO", "name": "Coburg", "region": "BY", "country": "DE"},
  {"code": "COC", "name": "Cochem-Zell", "region": "RP", "country": "DE"},
  {"code": "COE", "name": "Coesfeld", "region": "NRW", "country": "DE"},
  {"code": "CR", "name": "Crailsheim", "region": "BW", "country": "DE"},
  {"code": "CUX", "name": "Cuxhaven", "region": "NI", "country": "DE"},
  {"code": "CW", "name": "Calw", "region": "BW", "country": "DE"},
  {"code": "D", "name": "Düsseldorf", "region": "NRW", "country": "DE"},
  {"code": "DA", "name": "Darmstadt", "region": "HE", "country": "DE"},
  {"code": "DAH", "name": "Dachau", "region": "BY", "country": "DE"},
  {"code": "DAN", "name": "Lüchow-Dannenberg", "region": "NI", "country": "DE"},
  {"code": "DAU", "name": "Daun", "region": "RP", "country": "DE"},
  {"code": "DBR", "name": "Bad Doberan", "region": "MV", "country": "DE"},
  {"code": "DD", "name": "Dresden", "region": "SN", "country": "DE"},
  {"code": "DE", "name": "Dessau-Roßlau", "region": "ST", "country": "DE"},
  {"code": "DEG", "name": "Deggendorf", "region": "BY", "country": "DE"},
  {"code": "DEL", "name": "Delmenhorst", "region": "NI", "country": "DE"},
  {"code": "DGF", "name": "Dingolfing-Landau", "region": "BY", "country": "DE"},
  {"code": "DH", "name": "Diepholz", "region": "NI", "country": "DE"},
  {"code": "DI", "name": "Dieburg", "region": "HE", "country": "DE"},
  {"code": "DIL", "name": "Dillkreis (Dillenburg)", "region": "HE", "country": "DE"},
  {"code": "DIN", "name": "Dinslaken", "region": "NRW", "country": "DE"},
  {"code": "DIZ", "name": "Diez", "region": "RP", "country": "DE"},
  {"code": "DKB", "name": "Dinkelsbühl", "region": "BY", "country": "DE"},
  {"code": "DL", "name": "Döbeln", "region": "SN", "country": "DE"},
  {"code": "DLG", "name": "Dillingen a.d. Donau", "region": "BY", "country": "DE"},
  {"code": "DM", "name": "Demmin", "region": "MV", "country": "DE"},
  {"code": "DN", "name": "Düren", "region": "NRW", "country": "DE"},
  {"code": "DO", "name": "Dortmund", "region": "NRW", "country": "DE"},
  {"code": "DON", "name": "Donau-Ries (Donauwörth)", "region": "BY", "country": "DE"},
  {"code": "DS", "name": "Donaueschingen", "region": "BW", "country": "DE"},
  {"code": "DT", "name": "Lippe (Detmold)", "region": "NRW", "country": "DE"},
  {"code": "DU", "name": "Duisburg", "region": "NRW", "country": "DE"},
  {"code": "DUD", "name": "Duderstadt", "region": "NI", "country": "DE"},
  {"code": "DÜW", "name": "Bad Dürkheim", "region": "RP", "country": "DE"},
  {"code": "DW", "name": "Dippoldiswalde", "region": "SN", "country": "DE"},
  {"code": "DZ", "name": "Delitzsch", "region": "SN", "country": "DE"},
  {"code": "E", "name": "Essen", "region": "NRW", "country": "DE"},
  {"code": "EA", "name": "Eisenach", "region": "TH", "country": "DE"},
  {"code": "EB", "name": "Eilenburg", "region": "SN", "country": "DE"},
  {"code": "EBE", "name": "Ebersberg", "region": "BY", "country": "DE"},
  {"code": "EBN", "name": "Ebern", "region": "BY", "country": "DE"},
  {"code": "EBS", "name": "Ebermannstadt", "region": "BY", "country": "DE"},
  {"code": "ECK", "name": "Eckernförde", "region": "SH", "country": "DE"},
  {"code": "ED", "name": "Erding", "region": "BY", "country": "DE"},
  {"code": "EE", "name": "Elbe-Elster", "region": "BB", "country": "DE"},
  {"code": "EF", "name": "Erfurt", "region": "TH", "country": "DE"},
  {"code": "EG", "name": "Eggenfelden", "region": "BY", "country": "DE"},
  {"code": "EH", "name": "Eisenhüttenstadt", "region": "BB", "country": "DE"},
  {"code": "EHI", "name": "Ehingen (Donau)", "region": "BW", "country": "DE", "isDeprecated": true, "currentCode": "UL"},
  {"code": "EI", "name": "Eichstätt", "region": "BY", "country": "DE"},
  {"code": "EIC", "name": "Eichsfeld", "region": "TH", "country": "DE"},
  {"code": "EIH", "name": "Eichstätt", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "EI"},
  {"code": "EIL", "name": "Eisleben", "region": "ST", "country": "DE"},
  {"code": "EIN", "name": "Einbeck", "region": "NI", "country": "DE"},
  {"code": "EIS", "name": "Eisenberg", "region": "TH", "country": "DE"},
  {"code": "EL", "name": "Emsland", "region": "NI", "country": "DE"},
  {"code": "EM", "name": "Emmendingen", "region": "BW", "country": "DE"},
  {"code": "EMD", "name": "Emden", "region": "NI", "country": "DE"},
  {"code": "EMS", "name": "Rhein-Lahn-Kreis (Bad Ems)", "region": "RP", "country": "DE"},
  {"code": "EN", "name": "Ennepe-Ruhr-Kreis", "region": "NRW", "country": "DE"},
  {"code": "ER", "name": "Erlangen", "region": "BY", "country": "DE"},
  {"code": "ERB", "name": "Odenwaldkreis (Erbach)", "region": "HE", "country": "DE"},
  {"code": "ERH", "name": "Erlangen-Höchstadt", "region": "BY", "country": "DE"},
  {"code": "ERK", "name": "Erkelenz", "region": "NRW", "country": "DE"},
  {"code": "ERZ", "name": "Erzgebirgskreis", "region": "SN", "country": "DE"},
  {"code": "ES", "name": "Esslingen", "region": "BW", "country": "DE"},
  {"code": "ESB", "name": "Eschenbach in der Oberpfalz", "region": "BY", "country": "DE"},
  {"code": "ESA", "name": "Landkreis Eisenach", "region": "TH", "country": "DE", "isDeprecated": true, "currentCode": "WAK"},
  {"code": "ESW", "name": "Werra-Meißner-Kreis (Eschwege)", "region": "HE", "country": "DE"},
  {"code": "EU", "name": "Euskirchen", "region": "NRW", "country": "DE"},
  {"code": "EUT", "name": "Eutin", "region": "SH", "country": "DE", "isDeprecated": true, "currentCode": "OH"},
  {"code": "EW", "name": "Eberswalde", "region": "BB", "country": "DE"},
  {"code": "F", "name": "Frankfurt am Main", "region": "HE", "country": "DE"},
  {"code": "FAL", "name": "Fallingbostel", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "HK"},
  {"code": "FB", "name": "Wetteraukreis (Friedberg)", "region": "HE", "country": "DE"},
  {"code": "FD", "name": "Fulda", "region": "HE", "country": "DE"},
  {"code": "FDB", "name": "Friedberg", "region": "BY", "country": "DE"},
  {"code": "FDS", "name": "Freudenstadt", "region": "BW", "country": "DE"},
  {"code": "FEU", "name": "Feuchtwangen", "region": "BY", "country": "DE"},
  {"code": "FF", "name": "Frankfurt (Oder)", "region": "BB", "country": "DE"},
  {"code": "FFB", "name": "Fürstenfeldbruck", "region": "BY", "country": "DE"},
  {"code": "FG", "name": "Mittelsachsen (Freiberg)", "region": "SN", "country": "DE"},
  {"code": "FH", "name": "Main-Taunus-Kreis (Frankfurt / Main-Höchst)", "region": "HE", "country": "DE", "isDeprecated": true, "currentCode": "MTK"},
  {"code": "FI", "name": "Finsterwalde", "region": "BB", "country": "DE"},
  {"code": "FKB", "name": "Frankenberg (Eder)", "region": "HE", "country": "DE"},
  {"code": "FL", "name": "Flensburg", "region": "SH", "country": "DE"},
  {"code": "FLÖ", "name": "Flöha", "region": "SN", "country": "DE"},
  {"code": "FN", "name": "Bodenseekreis (Friedrichshafen)", "region": "BW", "country": "DE"},
  {"code": "FO", "name": "Forchheim", "region": "BY", "country": "DE"},
  {"code": "FOR", "name": "Forst", "region": "BB", "country": "DE"},
  {"code": "FR", "name": "Freiburg im Breisgau", "region": "BW", "country": "DE"},
  {"code": "FRG", "name": "Freyung-Grafenau", "region": "BY", "country": "DE"},
  {"code": "FRI", "name": "Friesland", "region": "NI", "country": "DE"},
  {"code": "FRW", "name": "Bad Freienwalde", "region": "BB", "country": "DE"},
  {"code": "FS", "name": "Freising", "region": "BY", "country": "DE"},
  {"code": "FT", "name": "Frankenthal", "region": "RP", "country": "DE"},
  {"code": "FTL", "name": "Freital", "region": "SN", "country": "DE"},
  {"code": "FÜ", "name": "Fürth", "region": "BY", "country": "DE"},
  {"code": "FÜS", "name": "Füssen", "region": "BY", "country": "DE"},
  {"code": "FW", "name": "Fürstenwalde", "region": "BB", "country": "DE"},
  {"code": "FZ", "name": "Fritzlar-Homberg", "region": "HE", "country": "DE"},
  {"code": "G", "name": "Gera", "region": "TH", "country": "DE"},
  {"code": "GA", "name": "Gardelegen", "region": "ST", "country": "DE"},
  {"code": "GAN", "name": "Bad Gandersheim", "region": "NI", "country": "DE"},
  {"code": "GAP", "name": "Garmisch-Partenkirchen", "region": "BY", "country": "DE"},
  {"code": "GC", "name": "Glauchau", "region": "SN", "country": "DE"},
  {"code": "GD", "name": "Schwäbisch Gmünd", "region": "BW", "country": "DE"},
  {"code": "GDB", "name": "Gadebusch", "region": "MV", "country": "DE"},
  {"code": "GE", "name": "Gelsenkirchen", "region": "NRW", "country": "DE"},
  {"code": "GEL", "name": "Geldern", "region": "NRW", "country": "DE"},
  {"code": "GEM", "name": "Gmünden am Main", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "MSP"},
  {"code": "GEO", "name": "Gerolzhofen", "region": "BY", "country": "DE"},
  {"code": "GER", "name": "Germersheim", "region": "RP", "country": "DE"},
  {"code": "GF", "name": "Gifhorn", "region": "NI", "country": "DE"},
  {"code": "GG", "name": "Groß-Gerau", "region": "HE", "country": "DE"},
  {"code": "GHA", "name": "Geithain", "region": "SN", "country": "DE"},
  {"code": "GHC", "name": "Gräfenhainichen", "region": "ST", "country": "DE"},
  {"code": "GI", "name": "Gießen", "region": "HE", "country": "DE"},
  {"code": "GK", "name": "Geilenkirchen-Heinsberg", "region": "NRW", "country": "DE"},
  {"code": "GL", "name": "Rheinisch-Bergischer Kreis (Bergisch Gladbach)", "region": "NRW", "country": "DE"},
  {"code": "GLA", "name": "Gladbeck", "region": "NRW", "country": "DE"},
  {"code": "GM", "name": "Oberbergischer Kreis (Gummersbach)", "region": "NRW", "country": "DE"},
  {"code": "GMN", "name": "Grimmen", "region": "MV", "country": "DE"},
  {"code": "GN", "name": "Gelnhausen", "region": "HE", "country": "DE"},
  {"code": "GNT", "name": "Genthin", "region": "ST", "country": "DE"},
  {"code": "GOA", "name": "Sankt Goar", "region": "RP", "country": "DE"},
  {"code": "GÖ", "name": "Göttingen", "region": "NI", "country": "DE"},
  {"code": "GOH", "name": "St. Goarshausen", "region": "RP", "country": "DE"},
  {"code": "GP", "name": "Göppingen", "region": "BW", "country": "DE"},
  {"code": "GR", "name": "Görlitz", "region": "SN", "country": "DE"},
  {"code": "GRA", "name": "Grafenau", "region": "BY", "country": "DE"},
  {"code": "GRH", "name": "Großenhain", "region": "SN", "country": "DE"},
  {"code": "GRI", "name": "Bad Griesbach i. Rottal", "region": "BY", "country": "DE"},
  {"code": "GRM", "name": "Grimma", "region": "SN", "country": "DE"},
  {"code": "GRS", "name": "Gransee", "region": "BB", "country": "DE", "isDeprecated": true, "currentCode": "OHV"},
  {"code": "GRZ", "name": "Greiz", "region": "TH", "country": "DE"},
  {"code": "GS", "name": "Goslar", "region": "NI", "country": "DE"},
  {"code": "GT", "name": "Gütersloh", "region": "NRW", "country": "DE"},
  {"code": "GTH", "name": "Gotha", "region": "TH", "country": "DE"},
  {"code": "GUB", "name": "Guben", "region": "BB", "country": "DE"},
  {"code": "GÜ", "name": "Güstrow", "region": "MV", "country": "DE"},
  {"code": "GUN", "name": "Gunzenhausen", "region": "BY", "country": "DE"},
  {"code": "GV", "name": "Grevenbroich", "region": "NRW", "country": "DE"},
  {"code": "GVM", "name": "Grevesmühlen", "region": "MV", "country": "DE"},
  {"code": "GW", "name": "Vorpommern-Greifswald", "region": "MV", "country": "DE"},
  {"code": "GZ", "name": "Günzburg", "region": "BY", "country": "DE"},
  {"code": "H", "name": "Hannover", "region": "NI", "country": "DE"},
  {"code": "HA", "name": "Hagen", "region": "NRW", "country": "DE"},
  {"code": "HAB", "name": "Hammelburg", "region": "BY", "country": "DE"},
  {"code": "HAL", "name": "Halle", "region": "ST", "country": "DE"},
  {"code": "HAM", "name": "Hamm", "region": "NRW", "country": "DE"},
  {"code": "HAS", "name": "Haßberge (Haßfurt)", "region": "BY", "country": "DE"},
  {"code": "HB", "name": "Hansestadt Bremen", "region": "HB", "country": "DE"},
  {"code": "HBN", "name": "Hildburghausen", "region": "TH", "country": "DE"},
  {"code": "HBS", "name": "Halberstadt", "region": "ST", "country": "DE"},
  {"code": "HC", "name": "Hainichen", "region": "SN", "country": "DE"},
  {"code": "HCH", "name": "Hechingen", "region": "BW", "country": "DE"},
  {"code": "HD", "name": "Heidelberg", "region": "BW", "country": "DE"},
  {"code": "HDH", "name": "Heidenheim (Brenz)", "region": "BW", "country": "DE"},
  {"code": "HDL", "name": "Haldensleben", "region": "ST", "country": "DE"},
  {"code": "HE", "name": "Helmstedt", "region": "NI", "country": "DE"},
  {"code": "HEB", "name": "Hersbruck", "region": "BY", "country": "DE"},
  {"code": "HEF", "name": "Hersfeld-Rotenburg", "region": "HE", "country": "DE"},
  {"code": "HEI", "name": "Dithmarschen (Heide)", "region": "SH", "country": "DE"},
  {"code": "HER", "name": "Herne", "region": "NRW", "country": "DE"},
  {"code": "HET", "name": "Hettstedt", "region": "ST", "country": "DE"},
  {"code": "HF", "name": "Herford", "region": "NRW", "country": "DE"},
  {"code": "HG", "name": "Hochtaunuskreis (Bad Homburg)", "region": "HE", "country": "DE"},
  {"code": "HGN", "name": "Hagenow", "region": "MV", "country": "DE"},
  {"code": "HGW", "name": "Greifswald", "region": "MV", "country": "DE"},
  {"code": "HH", "name": "Hansestadt Hamburg", "region": "HH", "country": "DE"},
  {"code": "HHM", "name": "Hohenmölsen", "region": "ST", "country": "DE"},
  {"code": "HI", "name": "Hildesheim", "region": "NI", "country": "DE"},
  {"code": "HIG", "name": "Heiligenstadt", "region": "TH", "country": "DE"},
  {"code": "HIP", "name": "Hilpoltstein", "region": "BY", "country": "DE"},
  {"code": "HK", "name": "Heidekreis", "region": "NI", "country": "DE"},
  {"code": "HL", "name": "Hansestadt Lübeck", "region": "SH", "country": "DE"},
  {"code": "HM", "name": "Hameln-Pyrmont", "region": "NI", "country": "DE"},
  {"code": "HMÜ", "name": "Hann. Münden", "region": "NI", "country": "DE"},
  {"code": "HN", "name": "Heilbronn", "region": "BW", "country": "DE"},
  {"code": "HO", "name": "Hof", "region": "BY", "country": "DE"},
  {"code": "HÖS", "name": "Erlangen-Höchstadt", "region": "BY", "country": "DE"},
  {"code": "HOG", "name": "Hofgeismar", "region": "HE", "country": "DE"},
  {"code": "HOH", "name": "Hofheim in Unterfranken", "region": "BY", "country": "DE"},
  {"code": "HOL", "name": "Holzminden", "region": "NI", "country": "DE"},
  {"code": "HOM", "name": "Saarpfalz-Kreis (Homburg)", "region": "SL", "country": "DE"},
  {"code": "HOR", "name": "Freudenstadt (Horb am Neckar)", "region": "BW", "country": "DE"},
  {"code": "HOT", "name": "Hohenstein-Ernstthal", "region": "SN", "country": "DE"},
  {"code": "HP", "name": "Kreis Bergstraße (Heppenheim)", "region": "HE", "country": "DE"},
  {"code": "HR", "name": "Schwalm-Eder-Kreis (Homberg)", "region": "HE", "country": "DE"},
  {"code": "HRO", "name": "Hansestadt Rostock", "region": "MV", "country": "DE"},
  {"code": "HS", "name": "Heinsberg", "region": "NRW", "country": "DE"},
  {"code": "HSK", "name": "Hochsauerlandkreis", "region": "NRW", "country": "DE"},
  {"code": "HST", "name": "Hansestadt Stralsund", "region": "MV", "country": "DE"},
  {"code": "HU", "name": "Hanau", "region": "HE", "country": "DE"},
  {"code": "HÜN", "name": "Hünfeld", "region": "HE", "country": "DE", "isDeprecated": true, "currentCode": "FD"},
  {"code": "HUS", "name": "Husum", "region": "SH", "country": "DE", "isDeprecated": true, "currentCode": "NF"},
  {"code": "HV", "name": "Havelberg", "region": "ST", "country": "DE"},
  {"code": "HVL", "name": "Havelland (Rathenow)", "region": "BB", "country": "DE"},
  {"code": "HW", "name": "Halle (Westfalen)", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "GT"},
  {"code": "HWI", "name": "Hansestadt Wismar", "region": "MV", "country": "DE"},
  {"code": "HX", "name": "Höxter", "region": "NRW", "country": "DE"},
  {"code": "HY", "name": "Hoyerswerda", "region": "SN", "country": "DE"},
  {"code": "HZ", "name": "Herzberg", "region": "BB", "country": "DE", "isDeprecated": true, "currentCode": "EE"},
  {"code": "HZ", "name": "Landkreis Harz", "region": "ST", "country": "DE"},
  {"code": "IGB", "name": "St. Ingbert", "region": "SL", "country": "DE"},
  {"code": "IK", "name": "Ilm-Kreis", "region": "TH", "country": "DE"},
  {"code": "IL", "name": "Ilmenau", "region": "TH", "country": "DE"},
  {"code": "ILL", "name": "Illertissen", "region": "BY", "country": "DE"},
  {"code": "IN", "name": "Ingolstadt", "region": "BY", "country": "DE"},
  {"code": "IS", "name": "Iserlohn", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "MK"},
  {"code": "IZ", "name": "Steinburg (Itzehoe)", "region": "SH", "country": "DE"},
  {"code": "J", "name": "Jena", "region": "TH", "country": "DE"},
  {"code": "JB", "name": "Jüterbog", "region": "BB", "country": "DE"},
  {"code": "JE", "name": "Jessen", "region": "ST", "country": "DE"},
  {"code": "JEV", "name": "Friesland (Jever)", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "FRI"},
  {"code": "JL", "name": "Jerichower Land", "region": "ST", "country": "DE"},
  {"code": "JÜL", "name": "Jülich", "region": "NRW", "country": "DE"},
  {"code": "K", "name": "Köln", "region": "NRW", "country": "DE"},
  {"code": "KA", "name": "Karlsruhe", "region": "BW", "country": "DE"},
  {"code": "KAR", "name": "Main-Spessart (Karlstadt)", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "MSP"},
  {"code": "KB", "name": "Waldeck-Frankenberg (Korbach)", "region": "HE", "country": "DE"},
  {"code": "KC", "name": "Kronach", "region": "BY", "country": "DE"},
  {"code": "KE", "name": "Kempten (Allgäu)", "region": "BY", "country": "DE"},
  {"code": "KEH", "name": "Kelheim", "region": "BY", "country": "DE"},
  {"code": "KEL", "name": "Kehl", "region": "BW", "country": "DE"},
  {"code": "KEM", "name": "Kemnath", "region": "BY", "country": "DE"},
  {"code": "KF", "name": "Kaufbeuren", "region": "BY", "country": "DE"},
  {"code": "KG", "name": "Bad Kissingen", "region": "BY", "country": "DE"},
  {"code": "KH", "name": "Bad Kreuznach", "region": "RP", "country": "DE"},
  {"code": "KI", "name": "Kiel", "region": "SH", "country": "DE"},
  {"code": "KIB", "name": "Donnersbergkreis (Kirchheimbolanden)", "region": "RP", "country": "DE"},
  {"code": "KK", "name": "Kempen-Krefeld", "region": "NRW", "country": "DE"},
  {"code": "KL", "name": "Kaiserslautern", "region": "RP", "country": "DE"},
  {"code": "KLE", "name": "Kleve", "region": "NRW", "country": "DE"},
  {"code": "KLZ", "name": "Klötze", "region": "ST", "country": "DE"},
  {"code": "KM", "name": "Kamenz", "region": "SN", "country": "DE"},
  {"code": "KN", "name": "Konstanz", "region": "BW", "country": "DE"},
  {"code": "KO", "name": "Koblenz", "region": "RP", "country": "DE"},
  {"code": "KÖN", "name": "Bad Königshofen i. Grabfeld", "region": "BY", "country": "DE"},
  {"code": "KÖT", "name": "Köthen", "region": "ST", "country": "DE"},
  {"code": "KÖZ", "name": "Kötzting", "region": "BY", "country": "DE"},
  {"code": "KR", "name": "Krefeld", "region": "NRW", "country": "DE"},
  {"code": "KRU", "name": "Krumbach", "region": "BY", "country": "DE"},
  {"code": "KS", "name": "Kassel", "region": "HE", "country": "DE"},
  {"code": "KT", "name": "Kitzingen", "region": "BY", "country": "DE"},
  {"code": "KU", "name": "Kulmbach", "region": "BY", "country": "DE"},
  {"code": "KÜN", "name": "Hohenlohekreis (Künzelsau)", "region": "BW", "country": "DE"},
  {"code": "KUS", "name": "Kusel", "region": "RP", "country": "DE"},
  {"code": "KW", "name": "Königs Wusterhausen", "region": "BB", "country": "DE"},
  {"code": "KY", "name": "Kyritz", "region": "BB", "country": "DE"},
  {"code": "KYF", "name": "Kyffhäuserkreis", "region": "TH", "country": "DE"},
  {"code": "L", "name": "Lahn-Dill-Kreis", "region": "HE", "country": "DE", "isDeprecated": true, "currentCode": "LDK, GI"},
  {"code": "L", "name": "Leipzig", "region": "SN", "country": "DE"},
  {"code": "LA", "name": "Landshut", "region": "BY", "country": "DE"},
  {"code": "LAN", "name": "Dingolfing-Landau", "region": "BY", "country": "DE"},
  {"code": "LAT", "name": "Vogelsbergkreis (Lauterbach)", "region": "HE", "country": "DE", "isDeprecated": true, "currentCode": "VB"},
  {"code": "LAU", "name": "Nürnberger Land (Lauf a.d. Pegnitz)", "region": "BY", "country": "DE"},
  {"code": "LB", "name": "Ludwigsburg", "region": "BW", "country": "DE"},
  {"code": "LBS", "name": "Lobenstein", "region": "TH", "country": "DE"},
  {"code": "LBZ", "name": "Lübz", "region": "MV", "country": "DE"},
  {"code": "LC", "name": "Luckau", "region": "BB", "country": "DE"},
  {"code": "LD", "name": "Landau in der Pfalz", "region": "RP", "country": "DE"},
  {"code": "LDK", "name": "Lahn-Dill-Kreis", "region": "HE", "country": "DE"},
  {"code": "LDS", "name": "Landkreis Dahme-Spreewald", "region": "BB", "country": "DE"},
  {"code": "LE", "name": "Lemgo", "region": "NRW", "country": "DE"},
  {"code": "LEO", "name": "Leonberg", "region": "BW", "country": "DE"},
  {"code": "LER", "name": "Leer", "region": "NI", "country": "DE"},
  {"code": "LEV", "name": "Leverkusen", "region": "NRW", "country": "DE"},
  {"code": "LF", "name": "Laufen", "region": "BY", "country": "DE"},
  {"code": "LG", "name": "Lüneburg", "region": "NI", "country": "DE"},
  {"code": "LH", "name": "Lüdinghausen", "region": "NRW", "country": "DE"},
  {"code": "LI", "name": "Lindau", "region": "BY", "country": "DE"},
  {"code": "LIB", "name": "Bad Liebenwerda", "region": "BB", "country": "DE"},
  {"code": "LIF", "name": "Lichtenfels", "region": "BY", "country": "DE"},
  {"code": "LIN", "name": "Lingen", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "EL"},
  {"code": "LIP", "name": "Lippe", "region": "NRW", "country": "DE"},
  {"code": "LK", "name": "Lübbecke", "region": "NRW", "country": "DE"},
  {"code": "LL", "name": "Landsberg am Lech", "region": "BY", "country": "DE"},
  {"code": "LM", "name": "Limburg-Weilburg", "region": "HE", "country": "DE"},
  {"code": "LN", "name": "Lübben", "region": "BB", "country": "DE"},
  {"code": "LÖ", "name": "Lörrach", "region": "BW", "country": "DE"},
  {"code": "LÖB", "name": "Löbau", "region": "SN", "country": "DE"},
  {"code": "LOH", "name": "Lohr am Main", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "MSP"},
  {"code": "LOS", "name": "Landkreis Oder-Spree", "region": "BB", "country": "DE"},
  {"code": "LP", "name": "Lippstadt", "region": "NRW", "country": "DE"},
  {"code": "LR", "name": "Lahr (Schwarzwald)", "region": "BW", "country": "DE"},
  {"code": "LRO", "name": "Landkreis Rostock", "region": "MV", "country": "DE"},
  {"code": "LS", "name": "Märkischer Kreis (Lüdenscheid)", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "MK"},
  {"code": "LSZ", "name": "Bad Langensalza", "region": "TH", "country": "DE"},
  {"code": "LU", "name": "Ludwigshafen am Rhein", "region": "RP", "country": "DE"},
  {"code": "LÜD", "name": "Lüdenscheid", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "MK"},
  {"code": "LÜN", "name": "Lünen", "region": "NRW", "country": "DE"},
  {"code": "LUK", "name": "Luckenwalde", "region": "BB", "country": "DE"},
  {"code": "LUP", "name": "Ludwigslust-Parchim", "region": "MV", "country": "DE"},
  {"code": "LWL", "name": "Ludwigslust", "region": "MV", "country": "DE"},
  {"code": "M", "name": "München", "region": "BY", "country": "DE"},
  {"code": "MA", "name": "Mannheim", "region": "BW", "country": "DE"},
  {"code": "MAB", "name": "Marienberg", "region": "SN", "country": "DE"},
  {"code": "MAI", "name": "Mainburg", "region": "BY", "country": "DE"},
  {"code": "MAK", "name": "Marktredwitz", "region": "BY", "country": "DE"},
  {"code": "MAL", "name": "Mallersdorf", "region": "BY", "country": "DE"},
  {"code": "MAR", "name": "Marktheidenfeld", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "MSP"},
  {"code": "MB", "name": "Miesbach", "region": "BY", "country": "DE"},
  {"code": "MC", "name": "Malchin", "region": "MV", "country": "DE"},
  {"code": "MD", "name": "Magdeburg", "region": "ST", "country": "DE"},
  {"code": "ME", "name": "Mettmann", "region": "NRW", "country": "DE"},
  {"code": "MED", "name": "Süderdithmarschen (Meldorf/Holstein)", "region": "SH", "country": "DE"},
  {"code": "MEG", "name": "Melsungen", "region": "HE", "country": "DE"},
  {"code": "MEI", "name": "Meißen", "region": "SN", "country": "DE"},
  {"code": "MEK", "name": "Mittlerer Erzgebirgskreis", "region": "SN", "country": "DE"},
  {"code": "MEL", "name": "Melle", "region": "NI", "country": "DE"},
  {"code": "MEP", "name": "Meppen", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "EL"},
  {"code": "MER", "name": "Merseburg", "region": "ST", "country": "DE"},
  {"code": "MES", "name": "Hochsauerlandkreis (Meschede)", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "HSK"},
  {"code": "MET", "name": "Mellrichstadt", "region": "BY", "country": "DE"},
  {"code": "MG", "name": "Mönchengladbach", "region": "NRW", "country": "DE"},
  {"code": "MGH", "name": "Bad Mergentheim", "region": "BW", "country": "DE"},
  {"code": "MGN", "name": "Meiningen", "region": "TH", "country": "DE"},
  {"code": "MH", "name": "Mühlheim an der Ruhr", "region": "NRW", "country": "DE"},
  {"code": "MHL", "name": "Mühlhausen", "region": "TH", "country": "DE"},
  {"code": "MI", "name": "Minden-Lübbecke", "region": "NRW", "country": "DE"},
  {"code": "MIL", "name": "Miltenberg", "region": "BY", "country": "DE"},
  {"code": "MK", "name": "Märkischer Kreis", "region": "NRW", "country": "DE"},
  {"code": "MKK", "name": "Main-Kinzig-Kreis", "region": "HE", "country": "DE"},
  {"code": "ML", "name": "Mansfelder Land", "region": "ST", "country": "DE"},
  {"code": "MM", "name": "Memmingen", "region": "BY", "country": "DE"},
  {"code": "MN", "name": "Unterallgäu (Mindelheim)", "region": "BY", "country": "DE"},
  {"code": "MO", "name": "Moers", "region": "NRW", "country": "DE"},
  {"code": "MOD", "name": "Marktoberdorf", "region": "BY", "country": "DE"},
  {"code": "MOL", "name": "Landkreis Märkisch-Oderland", "region": "BB", "country": "DE"},
  {"code": "MON", "name": "Monschau", "region": "NRW", "country": "DE"},
  {"code": "MOS", "name": "Neckar-Odenwald-Kreis (Mosbach)", "region": "BW", "country": "DE"},
  {"code": "MQ", "name": "Merseburg-Querfurt", "region": "ST", "country": "DE"},
  {"code": "MR", "name": "Marburg-Biedenkopf", "region": "HE", "country": "DE"},
  {"code": "MS", "name": "Münster", "region": "NRW", "country": "DE"},
  {"code": "MSE", "name": "Mecklenburgische Seenplatte", "region": "MV", "country": "DE"},
  {"code": "MSH", "name": "Mansfeld-Südharz", "region": "ST", "country": "DE"},
  {"code": "MSP", "name": "Main-Spessart (Karlstadt)", "region": "BY", "country": "DE"},
  {"code": "MST", "name": "Mecklenburg-Strelitz", "region": "MV", "country": "DE"},
  {"code": "MT", "name": "Westerwald (Montabaur)", "region": "RP", "country": "DE", "isDeprecated": true, "currentCode": "WW"},
  {"code": "MTK", "name": "Main-Taunus-Kreis", "region": "HE", "country": "DE"},
  {"code": "MTL", "name": "Muldentalkreis", "region": "SN", "country": "DE"},
  {"code": "MU", "name": "München Landkreis", "region": "BY", "country": "DE"},
  {"code": "MUC", "name": "München Stadt", "region": "BY", "country": "DE"},
  {"code": "MÜ", "name": "Mühldorf am Inn", "region": "BY", "country": "DE"},
  {"code": "MÜB", "name": "Münchberg", "region": "BY", "country": "DE"},
  {"code": "MÜL", "name": "Müllheim", "region": "BW", "country": "DE"},
  {"code": "MÜN", "name": "Münsingen (Württemberg)", "region": "BW", "country": "DE", "isDeprecated": true, "currentCode": "RT"},
  {"code": "MÜR", "name": "Müritz", "region": "MV", "country": "DE"},
  {"code": "MW", "name": "Mittweida", "region": "SN", "country": "DE"},
  {"code": "MY", "name": "Mayen", "region": "RP", "country": "DE"},
  {"code": "MYK", "name": "Mayen-Koblenz", "region": "RP", "country": "DE"},
  {"code": "MZ", "name": "Mainz", "region": "RP", "country": "DE"},
  {"code": "MZG", "name": "Merzig-Wadern", "region": "SL", "country": "DE"},
  {"code": "N", "name": "Nürnberg", "region": "BY", "country": "DE"},
  {"code": "NAB", "name": "Nabburg", "region": "BY", "country": "DE"},
  {"code": "NAI", "name": "Naila", "region": "BY", "country": "DE"},
  {"code": "NAU", "name": "Nauen", "region": "BB", "country": "DE"},
  {"code": "NB", "name": "Neubrandenburg", "region": "MV", "country": "DE"},
  {"code": "ND", "name": "Neuburg-Schrobenhausen", "region": "BY", "country": "DE"},
  {"code": "NDH", "name": "Nordhausen", "region": "TH", "country": "DE"},
  {"code": "NE", "name": "Neuss", "region": "NRW", "country": "DE"},
  {"code": "NEA", "name": "Neustadt an der Aisch-Bad Windsheim", "region": "BY", "country": "DE"},
  {"code": "NEB", "name": "Nebra", "region": "ST", "country": "DE"},
  {"code": "NEC", "name": "Neustadt b. Coburg", "region": "BY", "country": "DE"},
  {"code": "NEN", "name": "Neunburg vorm Wald", "region": "BY", "country": "DE"},
  {"code": "NES", "name": "Rhön-Grabfeld (Bad Neustadt a.d. Saale)", "region": "BY", "country": "DE"},
  {"code": "NEU", "name": "Hochschwarzwald (Titisee-Neustadt)", "region": "BW", "country": "DE"},
  {"code": "NEW", "name": "Neustadt an der Waldnaab", "region": "BY", "country": "DE"},
  {"code": "NF", "name": "Nordfriesland (Husum)", "region": "SH", "country": "DE"},
  {"code": "NH", "name": "Neuhaus", "region": "TH", "country": "DE"},
  {"code": "NI", "name": "Nienburg (Weser)", "region": "NI", "country": "DE"},
  {"code": "NIB", "name": "Süd Tondern (Niebüll)", "region": "SH", "country": "DE", "isDeprecated": true, "currentCode": "NF"},
  {"code": "NK", "name": "Neunkirchen (Saar)", "region": "SL", "country": "DE"},
  {"code": "NM", "name": "Neumarkt in der Oberpfalz", "region": "BY", "country": "DE"},
  {"code": "NMB", "name": "Naumburg", "region": "ST", "country": "DE"},
  {"code": "NMS", "name": "Neumünster", "region": "SH", "country": "DE"},
  {"code": "NÖ", "name": "Nördlingen", "region": "BY", "country": "DE"},
  {"code": "NOH", "name": "Grafschaft Bentheim (Nordhorn)", "region": "NI", "country": "DE"},
  {"code": "NOL", "name": "Niederschlesischer Oberlausitzkreis", "region": "SN", "country": "DE"},
  {"code": "NOM", "name": "Northeim", "region": "NI", "country": "DE"},
  {"code": "NOR", "name": "Norden", "region": "NI", "country": "DE"},
  {"code": "NP", "name": "Neuruppin", "region": "BB", "country": "DE"},
  {"code": "NR", "name": "Neuwied", "region": "RP", "country": "DE"},
  {"code": "NRÜ", "name": "Neustadt am Rübenberge", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "H"},
  {"code": "NT", "name": "Nürtingen", "region": "BW", "country": "DE"},
  {"code": "NU", "name": "Neu-Ulm", "region": "BY", "country": "DE"},
  {"code": "NVP", "name": "Nordvorpommern", "region": "MV", "country": "DE"},
  {"code": "NW", "name": "Neustadt an der Weinstraße", "region": "RP", "country": "DE"},
  {"code": "NWM", "name": "Nordwestmecklenburg", "region": "MV", "country": "DE"},
  {"code": "NY", "name": "Niesky", "region": "SN", "country": "DE"},
  {"code": "NZ", "name": "Neustrelitz", "region": "MV", "country": "DE"},
  {"code": "OA", "name": "Oberallgäu", "region": "BY", "country": "DE"},
  {"code": "OAL", "name": "Ostallgäu", "region": "BY", "country": "DE"},
  {"code": "OB", "name": "Oberhausen", "region": "NRW", "country": "DE"},
  {"code": "OBB", "name": "Obernburg a. Main", "region": "BY", "country": "DE"},
  {"code": "OBG", "name": "Osterburg", "region": "ST", "country": "DE"},
  {"code": "OC", "name": "Oschersleben", "region": "ST", "country": "DE"},
  {"code": "OCH", "name": "Ochsenfurt", "region": "BY", "country": "DE"},
  {"code": "OD", "name": "Stormarn (Bad Oldesloe)", "region": "SH", "country": "DE"},
  {"code": "OE", "name": "Olpe", "region": "NRW", "country": "DE"},
  {"code": "ÖHR", "name": "Öhringen", "region": "BW", "country": "DE"},
  {"code": "OF", "name": "Offenbach am Main", "region": "HE", "country": "DE"},
  {"code": "OG", "name": "Ortenaukreis (Offenburg)", "region": "BW", "country": "DE"},
  {"code": "OH", "name": "Ostholstein", "region": "SH", "country": "DE"},
  {"code": "OHA", "name": "Osterode am Harz", "region": "NI", "country": "DE"},
  {"code": "OHV", "name": "Oberhavel", "region": "BB", "country": "DE"},
  {"code": "OHZ", "name": "Osterholz", "region": "NI", "country": "DE"},
  {"code": "OK", "name": "Ohrekreis", "region": "ST", "country": "DE"},
  {"code": "OL", "name": "Oldenburg", "region": "NI", "country": "DE"},
  {"code": "OLD", "name": "Oldenburg in Holstein", "region": "SH", "country": "DE", "isDeprecated": true, "currentCode": "OH"},
  {"code": "OP", "name": "Rhein-Wupper-Kreis (Opladen)", "region": "NRW", "country": "DE"},
  {"code": "OPR", "name": "Ostprignitz-Ruppin", "region": "BB", "country": "DE"},
  {"code": "OR", "name": "Oranienburg", "region": "BB", "country": "DE", "isDeprecated": true, "currentCode": "OHV"},
  {"code": "OS", "name": "Osnabrück", "region": "NI", "country": "DE"},
  {"code": "OSL", "name": "Oberspreewald-Lausitz", "region": "BB", "country": "DE"},
  {"code": "OTT", "name": "Otterndorf", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "CUX"},
  {"code": "OTW", "name": "Ottweiler", "region": "SL", "country": "DE"},
  {"code": "OVI", "name": "Oberviechtach", "region": "BY", "country": "DE"},
  {"code": "OVL", "name": "Obervogtland", "region": "SN", "country": "DE"},
  {"code": "OVP", "name": "Ostvorpommern", "region": "MV", "country": "DE"},
  {"code": "OZ", "name": "Oschatz", "region": "SN", "country": "DE"},
  {"code": "P", "name": "Potsdam", "region": "BB", "country": "DE"},
  {"code": "PA", "name": "Passau", "region": "BY", "country": "DE"},
  {"code": "PAF", "name": "Pfaffenhofen a.d. Ilm", "region": "BY", "country": "DE"},
  {"code": "PAN", "name": "Rottal-Inn (Pfarrkirchen)", "region": "BY", "country": "DE"},
  {"code": "PAR", "name": "Parsberg", "region": "BY", "country": "DE"},
  {"code": "PB", "name": "Paderborn", "region": "NRW", "country": "DE"},
  {"code": "PCH", "name": "Parchim", "region": "MV", "country": "DE"},
  {"code": "PE", "name": "Peine", "region": "NI", "country": "DE"},
  {"code": "PEG", "name": "Pegnitz", "region": "BY", "country": "DE"},
  {"code": "PER", "name": "Perleberg", "region": "BB", "country": "DE", "isDeprecated": true, "currentCode": "PR"},
  {"code": "PF", "name": "Pforzheim", "region": "BW", "country": "DE"},
  {"code": "PI", "name": "Pinneberg", "region": "SH", "country": "DE"},
  {"code": "PIR", "name": "Sächsische Schweiz-Osterzgebirge (Pirna)", "region": "SN", "country": "DE"},
  {"code": "PK", "name": "Pritzwalk", "region": "BB", "country": "DE", "isDeprecated": true, "currentCode": "PR"},
  {"code": "PL", "name": "Plauen", "region": "SN", "country": "DE"},
  {"code": "PLÖ", "name": "Plön", "region": "SH", "country": "DE"},
  {"code": "PM", "name": "Potsdam-Mittelmark", "region": "BB", "country": "DE"},
  {"code": "PN", "name": "Pößneck", "region": "TH", "country": "DE"},
  {"code": "PR", "name": "Prignitz (Perleberg)", "region": "BB", "country": "DE"},
  {"code": "PRÜ", "name": "Prüm", "region": "RP", "country": "DE"},
  {"code": "PS", "name": "Pirmasens", "region": "RP", "country": "DE"},
  {"code": "PW", "name": "Pasewalk", "region": "MV", "country": "DE"},
  {"code": "PZ", "name": "Prenzlau", "region": "MV", "country": "DE"},
  {"code": "QFT", "name": "Querfurt", "region": "ST", "country": "DE"},
  {"code": "QLB", "name": "Quedlinburg", "region": "ST", "country": "DE"},
  {"code": "R", "name": "Regensburg", "region": "BY", "country": "DE"},
  {"code": "RA", "name": "Rastatt", "region": "BW", "country": "DE"},
  {"code": "RC", "name": "Reichenbach", "region": "SN", "country": "DE"},
  {"code": "RD", "name": "Rendsburg-Eckernförde", "region": "SH", "country": "DE"},
  {"code": "RDG", "name": "Ribnitz-Damgarten", "region": "MV", "country": "DE"},
  {"code": "RE", "name": "Recklinghausen", "region": "NRW", "country": "DE"},
  {"code": "REG", "name": "Regen", "region": "BY", "country": "DE"},
  {"code": "REH", "name": "Rehau", "region": "BY", "country": "DE"},
  {"code": "REI", "name": "Bad Reichenhall", "region": "BY", "country": "DE"},
  {"code": "RG", "name": "Riesa-Großenhain", "region": "SN", "country": "DE"},
  {"code": "RH", "name": "Roth", "region": "BY", "country": "DE"},
  {"code": "RI", "name": "Rinteln", "region": "NI", "country": "DE"},
  {"code": "RID", "name": "Riedenburg", "region": "BY", "country": "DE"},
  {"code": "RIE", "name": "Riesa", "region": "SN", "country": "DE"},
  {"code": "RL", "name": "Rochlitz", "region": "SN", "country": "DE"},
  {"code": "RM", "name": "Röbel (Müritz)", "region": "MV", "country": "DE"},
  {"code": "RN", "name": "Rathenow", "region": "BB", "country": "DE"},
  {"code": "RO", "name": "Rosenheim", "region": "BY", "country": "DE"},
  {"code": "ROD", "name": "Roding", "region": "BY", "country": "DE"},
  {"code": "ROF", "name": "Rotenburg an der Fulda", "region": "HE", "country": "DE"},
  {"code": "ROK", "name": "Rockenhausen", "region": "RP", "country": "DE"},
  {"code": "ROL", "name": "Rottenburg a.d. Laaber", "region": "BY", "country": "DE"},
  {"code": "ROS", "name": "Rostock", "region": "MV", "country": "DE"},
  {"code": "ROT", "name": "Rothenburg o.d. Tauber", "region": "BY", "country": "DE"},
  {"code": "ROW", "name": "Rotenburg (Wümme)", "region": "NI", "country": "DE"},
  {"code": "RP", "name": "Rhein-Pfalz-Kreis", "region": "RP", "country": "DE"},
  {"code": "RS", "name": "Remscheid", "region": "NRW", "country": "DE"},
  {"code": "RSL", "name": "Roßlau", "region": "ST", "country": "DE"},
  {"code": "RT", "name": "Reutlingen", "region": "BW", "country": "DE"},
  {"code": "RU", "name": "Rudolstadt", "region": "TH", "country": "DE"},
  {"code": "RÜD", "name": "Rheingau-Taunus-Kreis", "region": "HE", "country": "DE"},
  {"code": "RÜG", "name": "Rügen", "region": "MV", "country": "DE"},
  {"code": "RV", "name": "Ravensburg", "region": "BW", "country": "DE"},
  {"code": "RW", "name": "Rottweil", "region": "BW", "country": "DE"},
  {"code": "RY", "name": "Rheydt", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "MG"},
  {"code": "RZ", "name": "Herzogtum Lauenburg (Ratzeburg)", "region": "SH", "country": "DE"},
  {"code": "S", "name": "Stuttgart", "region": "BW", "country": "DE"},
  {"code": "SAB", "name": "Saarburg", "region": "RP", "country": "DE"},
  {"code": "SAD", "name": "Schwandorf", "region": "BY", "country": "DE"},
  {"code": "SÄK", "name": "Säckingen", "region": "BW", "country": "DE"},
  {"code": "SAN", "name": "Stadtsteinach", "region": "BY", "country": "DE"},
  {"code": "SAW", "name": "Altmarkkreis Salzwedel", "region": "ST", "country": "DE"},
  {"code": "SB", "name": "Saarbrücken", "region": "SL", "country": "DE"},
  {"code": "SBG", "name": "Strasburg", "region": "MV", "country": "DE"},
  {"code": "SBK", "name": "Schönebeck", "region": "ST", "country": "DE"},
  {"code": "SC", "name": "Schwabach", "region": "BY", "country": "DE"},
  {"code": "SCZ", "name": "Schleiz", "region": "TH", "country": "DE"},
  {"code": "SDH", "name": "Sondershausen", "region": "TH", "country": "DE"},
  {"code": "SDL", "name": "Stendal", "region": "ST", "country": "DE"},
  {"code": "SDT", "name": "Schwedt (Oder)", "region": "BB", "country": "DE"},
  {"code": "SE", "name": "Segeberg", "region": "SH", "country": "DE"},
  {"code": "SEB", "name": "Sebnitz", "region": "SN", "country": "DE"},
  {"code": "SEE", "name": "Seelow", "region": "BB", "country": "DE"},
  {"code": "SEF", "name": "Scheinfeld", "region": "BY", "country": "DE"},
  {"code": "SEL", "name": "Selb", "region": "BY", "country": "DE"},
  {"code": "SF", "name": "Sonthofen", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "OA"},
  {"code": "SFA", "name": "Soltau-Fallingbostel", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "HK"},
  {"code": "SFB", "name": "Senftenberg", "region": "BB", "country": "DE"},
  {"code": "SFT", "name": "Staßfurt", "region": "ST", "country": "DE"},
  {"code": "SG", "name": "Solingen", "region": "NRW", "country": "DE"},
  {"code": "SGH", "name": "Sangerhausen", "region": "ST", "country": "DE"},
  {"code": "SHA", "name": "Schwäbisch Hall", "region": "BW", "country": "DE"},
  {"code": "SHG", "name": "Schaumburg", "region": "NI", "country": "DE"},
  {"code": "SHK", "name": "Saale-Holzland-Kreis", "region": "TH", "country": "DE"},
  {"code": "SHL", "name": "Suhl", "region": "TH", "country": "DE"},
  {"code": "SI", "name": "Siegen-Wittgenstein", "region": "NRW", "country": "DE"},
  {"code": "SIG", "name": "Sigmaringen", "region": "BW", "country": "DE"},
  {"code": "SIM", "name": "Rhein-Hunsrück-Kreis (Simmern)", "region": "RP", "country": "DE"},
  {"code": "SK", "name": "Saalekreis", "region": "ST", "country": "DE"},
  {"code": "SL", "name": "Schleswig-Flensburg", "region": "SH", "country": "DE"},
  {"code": "SLE", "name": "Schleiden", "region": "NRW", "country": "DE"},
  {"code": "SLF", "name": "Saalfeld-Rudolstadt", "region": "TH", "country": "DE"},
  {"code": "SLG", "name": "Saulgau (Württemberg)", "region": "BW", "country": "DE"},
  {"code": "SLK", "name": "Salzlandkreis", "region": "ST", "country": "DE"},
  {"code": "SLN", "name": "Schmölln", "region": "TH", "country": "DE"},
  {"code": "SLS", "name": "Saarlouis", "region": "SL", "country": "DE"},
  {"code": "SLÜ", "name": "Schlüchtern", "region": "HE", "country": "DE"},
  {"code": "SLZ", "name": "Bad Salzungen", "region": "TH", "country": "DE"},
  {"code": "SM", "name": "Schmalkalden-Meiningen", "region": "TH", "country": "DE"},
  {"code": "SMÜ", "name": "Schwabmünchen", "region": "BY", "country": "DE"},
  {"code": "SN", "name": "Schwerin", "region": "MV", "country": "DE"},
  {"code": "SNH", "name": "Sinsheim", "region": "BW", "country": "DE", "isDeprecated": true, "currentCode": "HD"},
  {"code": "SO", "name": "Soest", "region": "NRW", "country": "DE"},
  {"code": "SOB", "name": "Schrobenhausen", "region": "BY", "country": "DE"},
  {"code": "SOL", "name": "Soltau", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "HK"},
  {"code": "SÖM", "name": "Sömmerda", "region": "TH", "country": "DE"},
  {"code": "SOG", "name": "Schongau", "region": "BY", "country": "DE"},
  {"code": "SOK", "name": "Saale-Orla-Kreis (Schleiz)", "region": "TH", "country": "DE"},
  {"code": "SON", "name": "Sonneberg", "region": "TH", "country": "DE"},
  {"code": "SP", "name": "Speyer", "region": "RP", "country": "DE"},
  {"code": "SPB", "name": "Spremberg", "region": "BB", "country": "DE"},
  {"code": "SPN", "name": "Spree-Neiße", "region": "BB", "country": "DE"},
  {"code": "SPR", "name": "Springe", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "H"},
  {"code": "SR", "name": "Straubing (-Bogen)", "region": "BY", "country": "DE"},
  {"code": "SRB", "name": "Strausberg", "region": "BB", "country": "DE"},
  {"code": "SRO", "name": "Stadtroda", "region": "TH", "country": "DE"},
  {"code": "ST", "name": "Steinfurt", "region": "NRW", "country": "DE"},
  {"code": "STA", "name": "Starnberg", "region": "BY", "country": "DE"},
  {"code": "STB", "name": "Sternberg", "region": "MV", "country": "DE"},
  {"code": "STD", "name": "Stade", "region": "NI", "country": "DE"},
  {"code": "STE", "name": "Staffelstein", "region": "BY", "country": "DE"},
  {"code": "STH", "name": "Schaumburg-Lippe (Stadthagen)", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "SHG"},
  {"code": "STL", "name": "Stollberg", "region": "SN", "country": "DE"},
  {"code": "STO", "name": "Stockach", "region": "BW", "country": "DE"},
  {"code": "SU", "name": "Rhein-Sieg-Kreis (Siegburg)", "region": "NRW", "country": "DE"},
  {"code": "SÜW", "name": "Südliche Weinstraße", "region": "RP", "country": "DE"},
  {"code": "SUL", "name": "Sulzbach-Rosenberg", "region": "BY", "country": "DE"},
  {"code": "SW", "name": "Schweinfurt", "region": "BY", "country": "DE"},
  {"code": "SWA", "name": "Rheingau-Taunus-Kreis", "region": "HE", "country": "DE"},
  {"code": "SY", "name": "Grafschaft Hoya (Syke)", "region": "NI", "country": "DE"},
  {"code": "SZ", "name": "Salzgitter", "region": "NI", "country": "DE"},
  {"code": "SZB", "name": "Schwarzenberg", "region": "SN", "country": "DE"},
  {"code": "TBB", "name": "Main-Tauber-Kreis (Tauberbischofsheim)", "region": "BW", "country": "DE"},
  {"code": "TDO", "name": "Torgau, Delitzsch, Oschatz (Nordsachsen)", "region": "SN", "country": "DE"},
  {"code": "TE", "name": "Tecklenburg", "region": "NRW", "country": "DE"},
  {"code": "TET", "name": "Teterow", "region": "MV", "country": "DE"},
  {"code": "TF", "name": "Teltow-Fläming", "region": "BB", "country": "DE"},
  {"code": "TG", "name": "Torgau", "region": "SN", "country": "DE"},
  {"code": "TIR", "name": "Tirschenreuth", "region": "BY", "country": "DE"},
  {"code": "TO", "name": "Torgau-Oschatz", "region": "SN", "country": "DE"},
  {"code": "TÖL", "name": "Bad Tölz-Wolfratshausen", "region": "BY", "country": "DE"},
  {"code": "TÖN", "name": "Eiderstedt (Tönning)", "region": "SH", "country": "DE", "isDeprecated": true, "currentCode": "NF"},
  {"code": "TP", "name": "Templin", "region": "BB", "country": "DE"},
  {"code": "TR", "name": "Trier", "region": "RP", "country": "DE"},
  {"code": "TS", "name": "Traunstein", "region": "BY", "country": "DE"},
  {"code": "TT", "name": "Tettnang (Württemberg)", "region": "BW", "country": "DE"},
  {"code": "TÜ", "name": "Tübingen", "region": "BW", "country": "DE"},
  {"code": "TUT", "name": "Tuttlingen", "region": "BW", "country": "DE"},
  {"code": "UE", "name": "Uelzen", "region": "NI", "country": "DE"},
  {"code": "UEM", "name": "Ueckermünde", "region": "MV", "country": "DE"},
  {"code": "ÜB", "name": "Überlingen am Bodensee", "region": "BW", "country": "DE"},
  {"code": "UER", "name": "Uecker-Randow", "region": "MV", "country": "DE"},
  {"code": "UFF", "name": "Uffenheim", "region": "BY", "country": "DE"},
  {"code": "UH", "name": "Unstrut-Hainich-Kreis", "region": "TH", "country": "DE"},
  {"code": "UL", "name": "Ulm", "region": "BW", "country": "DE"},
  {"code": "UM", "name": "Uckermark", "region": "BB", "country": "DE"},
  {"code": "UN", "name": "Unna", "region": "NRW", "country": "DE"},
  {"code": "USI", "name": "Usingen", "region": "HE", "country": "DE"},
  {"code": "V", "name": "Vogtlandkreis", "region": "SN", "country": "DE"},
  {"code": "VAI", "name": "Vaihingen an der Enz", "region": "BW", "country": "DE"},
  {"code": "VB", "name": "Vogelsbergkreis", "region": "HE", "country": "DE"},
  {"code": "VEC", "name": "Vechta", "region": "NI", "country": "DE"},
  {"code": "VER", "name": "Verden", "region": "NI", "country": "DE"},
  {"code": "VG", "name": "Vorpommern-Greifswald", "region": "MV", "country": "DE"},
  {"code": "VIB", "name": "Vilsbiburg", "region": "BY", "country": "DE"},
  {"code": "VIE", "name": "Viersen", "region": "NRW", "country": "DE"},
  {"code": "VIT", "name": "Viechtach", "region": "BY", "country": "DE"},
  {"code": "VK", "name": "Völklingen", "region": "SL", "country": "DE"},
  {"code": "VL", "name": "Villingen (Schwarzwald)", "region": "BW", "country": "DE", "isDeprecated": true, "currentCode": "VS"},
  {"code": "VOF", "name": "Vilshofen", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "PA"},
  {"code": "VOH", "name": "Vohenstrauß", "region": "BY", "country": "DE"},
  {"code": "VR", "name": "Vorpommern-Rügen", "region": "MV", "country": "DE"},
  {"code": "VS", "name": "Schwarzwald-Baar-Kreis (Villingen-Schwenningen)", "region": "BW", "country": "DE"},
  {"code": "W", "name": "Wuppertal", "region": "NRW", "country": "DE"},
  {"code": "WA", "name": "Waldeck", "region": "HE", "country": "DE"},
  {"code": "WAF", "name": "Warendorf", "region": "NRW", "country": "DE"},
  {"code": "WAK", "name": "Wartburgkreis", "region": "TH", "country": "DE"},
  {"code": "WAN", "name": "Wanne-Eickel", "region": "NRW", "country": "DE"},
  {"code": "WAR", "name": "Warburg", "region": "NRW", "country": "DE"},
  {"code": "WAT", "name": "Wattenscheid", "region": "NRW", "country": "DE"},
  {"code": "WB", "name": "Wittenberg", "region": "ST", "country": "DE"},
  {"code": "WBG", "name": "Wolfsburg", "region": "NI", "country": "DE"},
  {"code": "WBS", "name": "Worbis", "region": "TH", "country": "DE"},
  {"code": "WD", "name": "Wiedenbrück", "region": "NRW", "country": "DE", "isDeprecated": true, "currentCode": "GT"},
  {"code": "WDA", "name": "Werdau", "region": "SN", "country": "DE"},
  {"code": "WE", "name": "Weimar", "region": "TH", "country": "DE"},
  {"code": "WEB", "name": "Oberwesterwaldkreis (Westerburg)", "region": "RP", "country": "DE", "isDeprecated": true, "currentCode": "WW"},
  {"code": "WEG", "name": "Wegscheid", "region": "BY", "country": "DE", "isDeprecated": true, "currentCode": "PA"},
  {"code": "WEL", "name": "Weilburg", "region": "HE", "country": "DE"},
  {"code": "WEM", "name": "Wesermünde (Bremerhaven)", "region": "NI", "country": "DE", "isDeprecated": true, "currentCode": "CUX"},
  {"code": "WEN", "name": "Weiden i. d. Oberpfalz", "region": "BY", "country": "DE"},
  {"code": "WER", "name": "Wertingen", "region": "BY", "country": "DE"},
  {"code": "WES", "name": "Wesel", "region": "NRW", "country": "DE"},
  {"code": "WF", "name": "Wolfenbüttel", "region": "NI", "country": "DE"},
  {"code": "WG", "name": "Wangen im Allgäu", "region": "BW", "country": "DE"},
  {"code": "WHV", "name": "Wilhelmshaven", "region": "NI", "country": "DE"},
  {"code": "WI", "name": "Wiesbaden", "region": "HE", "country": "DE"},
  {"code": "WIL", "name": "Wittlich", "region": "RP", "country": "DE"},
  {"code": "WIS", "name": "Wismar", "region": "MV", "country": "DE"},
  {"code": "WIT", "name": "Witten", "region": "NRW", "country": "DE"},
  {"code": "WIZ", "name": "Witzenhausen", "region": "HE", "country": "DE"},
  {"code": "WK", "name": "Wittstock", "region": "BB", "country": "DE"},
  {"code": "WL", "name": "Harburg (Winsen/Luhe)", "region": "NI", "country": "DE"},
  {"code": "WLG", "name": "Wolgast", "region": "MV", "country": "DE"},
  {"code": "WM", "name": "Weilheim-Schongau", "region": "BY", "country": "DE"},
  {"code": "WMS", "name": "Wolmirstedt", "region": "ST", "country": "DE"},
  {"code": "WN", "name": "Rems-Murr-Kreis (Waiblingen)", "region": "BW", "country": "DE"},
  {"code": "WND", "name": "St. Wendel", "region": "SL", "country": "DE"},
  {"code": "WO", "name": "Worms", "region": "RP", "country": "DE"},
  {"code": "WOB", "name": "Wolfsburg", "region": "NI", "country": "DE"},
  {"code": "WOH", "name": "Wolfhagen", "region": "HE", "country": "DE"},
  {"code": "WOL", "name": "Wolfach", "region": "BW", "country": "DE"},
  {"code": "WOR", "name": "Wolfratshausen", "region": "BY", "country": "DE"},
  {"code": "WOS", "name": "Wolfstein", "region": "BY", "country": "DE"},
  {"code": "WR", "name": "Wernigerode", "region": "ST", "country": "DE"},
  {"code": "WRN", "name": "Waren", "region": "MV", "country": "DE"},
  {"code": "WS", "name": "Wasserburg am Inn", "region": "BY", "country": "DE"},
  {"code": "WSF", "name": "Weißenfels", "region": "ST", "country": "DE"},
  {"code": "WST", "name": "Ammerland (Westerstede)", "region": "NI", "country": "DE"},
  {"code": "WSW", "name": "Weißwasser", "region": "SN", "country": "DE"},
  {"code": "WT", "name": "Waldshut", "region": "BW", "country": "DE"},
  {"code": "WTL", "name": "Wittlage", "region": "NI", "country": "DE"},
  {"code": "WTM", "name": "Wittmund", "region": "NI", "country": "DE"},
  {"code": "WÜ", "name": "Würzburg", "region": "BY", "country": "DE"},
  {"code": "WÜM", "name": "Waldmünchen", "region": "BY", "country": "DE"},
  {"code": "WUG", "name": "Weißenburg-Gunzenhausen", "region": "BY", "country": "DE"},
  {"code": "WUN", "name": "Wunsiedel", "region": "BY", "country": "DE"},
  {"code": "WUR", "name": "Wurzen", "region": "SN", "country": "DE"},
  {"code": "WW", "name": "Westerwaldkreis", "region": "RP", "country": "DE"},
  {"code": "WZ", "name": "Wetzlar", "region": "HE", "country": "DE"},
  {"code": "WZL", "name": "Wanzleben", "region": "ST", "country": "DE"},
  {"code": "Z", "name": "Zwickau", "region": "SN", "country": "DE"},
  {"code": "ZE", "name": "Zerbst", "region": "ST", "country": "DE"},
  {"code": "ZEL", "name": "Zell (Mosel)", "region": "RP", "country": "DE"},
  {"code": "ZI", "name": "Löbau-Zittau", "region": "SN", "country": "DE"},
  {"code": "ZIG", "name": "Ziegenhain (Schwalm-Eder-Kreis)", "region": "HE", "country": "DE"},
  {"code": "ZP", "name": "Zschopau", "region": "SN", "country": "DE"},
  {"code": "ZR", "name": "Zeulenroda", "region": "TH", "country": "DE"},
  {"code": "ZS", "name": "Zossen", "region": "BB", "country": "DE"},
  {"code": "ZW", "name": "Zweibrücken", "region": "RP", "country": "DE"},
  {"code": "ZZ", "name": "Zeitz", "region": "ST", "country": "DE"}
];